// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M' | 'S' // Variant
}} Props

 */
import { stdin_default } from "../chunks/chunk-VQ6CFIHF.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-IUVHVVOX.js";
import { className, css, fonts } from "../chunks/chunk-6RBWXANE.js";
import "../chunks/chunk-JOQ27WRR.js";
import { routes } from "../chunks/chunk-XIXCBJDO.js";

// virtual:navigation/footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rwl5iJ0Jlsh6kuCR8K00/UylnUgsGBYl8I7g1tDnJ/LT0gX9mtu.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var NavigationTextHoverFonts = getFonts(stdin_default);
var cycleOrder = ["hDiagrBhX", "PpWX9Nzcf", "tAhy0cIZG"];
var serializationHash = "framer-TSZIr";
var variantClassNames = {
	hDiagrBhX: "framer-v-z20imy",
	PpWX9Nzcf: "framer-v-5vmnq2",
	tAhy0cIZG: "framer-v-1mpq8ij",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	L: "hDiagrBhX",
	M: "PpWX9Nzcf",
	S: "tAhy0cIZG",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "hDiagrBhX",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "hDiagrBhX",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-z20imy",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"hDiagrBhX"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color":
								"var(--token-d86f1591-0c16-44cd-be10-19334dfa9293, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							background:
								"conic-gradient(from 0deg at 50% 0%, rgb(0, 0, 0) 90deg, rgba(79, 26, 214, 0.4) 181.2985641891892deg, rgb(0, 0, 0) 270deg)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								PpWX9Nzcf: {
									"data-framer-name": "M",
								},
								tAhy0cIZG: {
									"data-framer-name": "S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-qluo01"}
							data-framer-name={"Top"}
							layoutDependency={layoutDependency}
							layoutId={"xsGetvW6A"}
						>
							<motion.div
								className={"framer-1njellx"}
								data-framer-name={"Left"}
								layoutDependency={layoutDependency}
								layoutId={"BfOnewf1_"}
							>
								<Link
									href={{
										webPageId: "augiA20Il",
									}}
									motionChild={true}
									nodeId={"T22GGVXgH"}
									scopeId={"LT0gX9mtu"}
								>
									<Image
										as={"a"}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 100 + 0 + 0 + 0 + 0,
											),
											pixelHeight: 1024,
											pixelWidth: 1024,
											sizes: "176px",
											src: "https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?width=1024&height=1024",
											srcSet:
												"https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?width=1024&height=1024 1024w",
										}}
										className={"framer-1xq6p9a framer-1ukbytl"}
										data-framer-name={"Logo"}
										layoutDependency={layoutDependency}
										layoutId={"T22GGVXgH"}
										{...addPropertyOverrides(
											{
												PpWX9Nzcf: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																100 +
																0 +
																0 +
																0 +
																0 +
																0,
														),
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "176px",
														src: "https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?width=1024&height=1024 1024w",
													},
												},
												tAhy0cIZG: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																50 +
																0 +
																0 +
																0 +
																0 +
																0,
														),
														pixelHeight: 1024,
														pixelWidth: 1024,
														sizes: "176px",
														src: "https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?width=1024&height=1024",
														srcSet:
															"https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?scale-down-to=512&width=1024&height=1024 512w,https://framerusercontent.com/images/UV0s8dfHekymslqdwTicnml2o.png?width=1024&height=1024 1024w",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</Link>
								<motion.div
									className={"framer-mhuyew"}
									data-framer-name={"Seperator"}
									layoutDependency={layoutDependency}
									layoutId={"DBZ2bDlfv"}
									style={{
										background:
											"linear-gradient(90.00000000000075deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0) 100%)",
									}}
								/>
								<motion.div
									className={"framer-1xy8ipc"}
									data-framer-name={"Body Text"}
									layoutDependency={layoutDependency}
									layoutId={"nQ9UW7xF3"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-4s96la"}
										data-framer-name={"Text"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"t1gxvFAMs"}
										style={{
											"--extracted-143mgqx": "rgb(255, 255, 255)",
											"--extracted-1w3ko1f":
												"var(--token-d2ee1de5-88f8-41d7-8642-338767096a94, rgba(255, 255, 255, 0.5))",
											"--extracted-3sq8v0":
												"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
											"--extracted-41musj":
												"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
											"--extracted-c9yw3e":
												"var(--token-d2ee1de5-88f8-41d7-8642-338767096a94, rgba(255, 255, 255, 0.5))",
											"--extracted-dfbufw":
												"var(--token-d2ee1de5-88f8-41d7-8642-338767096a94, rgba(255, 255, 255, 0.5))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-x0s9r5"}
												data-styles-preset={"QhK6qqT5U"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-1w3ko1f, var(--token-d2ee1de5-88f8-41d7-8642-338767096a94, rgba(255, 255, 255, 0.5)))",
													}}
												>
													{"Made with calm chaos "}
												</motion.span>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-3sq8v0, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)))",
													}}
												>
													{"\u{1F49C}"}
												</motion.span>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-c9yw3e, var(--token-d2ee1de5-88f8-41d7-8642-338767096a94, rgba(255, 255, 255, 0.5)))",
													}}
												>
													{" and passion by"}
												</motion.span>
												<motion.br />
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-dfbufw, var(--token-d2ee1de5-88f8-41d7-8642-338767096a94, rgba(255, 255, 255, 0.5)))",
													}}
												>
													{"- "}
												</motion.span>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-143mgqx, rgb(255, 255, 255))",
													}}
												>
													{"Pratham Shirbhate in Mumbai."}
												</motion.span>
												<motion.span
													style={{
														"--framer-text-color":
															"var(--extracted-41musj, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)))",
													}}
												>
													{"."}
												</motion.span>
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-fnx7o9"}
								data-framer-name={"Right"}
								layoutDependency={layoutDependency}
								layoutId={"ezpvOwIax"}
							>
								<motion.div
									className={"framer-1jltczg"}
									data-framer-name={"Pages"}
									layoutDependency={layoutDependency}
									layoutId={"A8xdQRaRA"}
								>
									<motion.div
										className={"framer-wdq88k"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"BnSyQ9NLj"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1rl1jwu"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"xzDyBo33B"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h4
													className={"framer-styles-preset-1ing3ma"}
													data-styles-preset={"VnmEZ_3BZ"}
												>
													{"Website Pages"}
												</motion.h4>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-pxkf8m"}
										data-framer-name={"Navigation/Menu Items"}
										layoutDependency={layoutDependency}
										layoutId={"Xhy1sIdeV"}
									>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													height={26}
													y={
														(componentViewport?.y || 0) +
														100 +
														0 +
														0 +
														0 +
														0 +
														38 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															PpWX9Nzcf: {
																y:
																	(componentViewport?.y || 0) +
																	100 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	38 +
																	0 +
																	0,
															},
															tAhy0cIZG: {
																y:
																	(componentViewport?.y || 0) +
																	50 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	0 +
																	38 +
																	0 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-as62wa-container"}
														layoutDependency={layoutDependency}
														layoutId={"ZZbCrbniF-container"}
														nodeId={"ZZbCrbniF"}
														rendersWithMotion={true}
														scopeId={"LT0gX9mtu"}
													>
														{_jsx(stdin_default, {
															aLnDlFZKR: resolvedLinks[0],
															Cn6fz_Vow: "Home",
															height: "100%",
															id: "ZZbCrbniF",
															layoutId: "ZZbCrbniF",
															TqaTpTiSx: false,
															variant: "vbxf8HL8_",
															width: "100%",
															X2yrtSssb: false,
															...addPropertyOverrides(
																{
																	PpWX9Nzcf: {
																		aLnDlFZKR: resolvedLinks[1],
																	},
																	tAhy0cIZG: {
																		aLnDlFZKR: resolvedLinks[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "hetOMwTYW",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "hetOMwTYW",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "hetOMwTYW",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks1) => (
												<ComponentViewportProvider
													height={26}
													y={
														(componentViewport?.y || 0) +
														100 +
														0 +
														0 +
														0 +
														0 +
														38 +
														0 +
														36
													}
													{...addPropertyOverrides(
														{
															PpWX9Nzcf: {
																y:
																	(componentViewport?.y || 0) +
																	100 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	38 +
																	0 +
																	36,
															},
															tAhy0cIZG: {
																y:
																	(componentViewport?.y || 0) +
																	50 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	0 +
																	38 +
																	0 +
																	36,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-gketd9-container"}
														layoutDependency={layoutDependency}
														layoutId={"d_cMne_0x-container"}
														nodeId={"d_cMne_0x"}
														rendersWithMotion={true}
														scopeId={"LT0gX9mtu"}
													>
														{_jsx(stdin_default, {
															aLnDlFZKR: resolvedLinks1[0],
															Cn6fz_Vow: "About Me",
															height: "100%",
															id: "d_cMne_0x",
															layoutId: "d_cMne_0x",
															TqaTpTiSx: false,
															variant: "vbxf8HL8_",
															width: "100%",
															X2yrtSssb: false,
															...addPropertyOverrides(
																{
																	PpWX9Nzcf: {
																		aLnDlFZKR: resolvedLinks1[1],
																	},
																	tAhy0cIZG: {
																		aLnDlFZKR: resolvedLinks1[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "ADJCSktRp",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "ADJCSktRp",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "ADJCSktRp",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks2) => (
												<ComponentViewportProvider
													height={26}
													y={
														(componentViewport?.y || 0) +
														100 +
														0 +
														0 +
														0 +
														0 +
														38 +
														0 +
														72
													}
													{...addPropertyOverrides(
														{
															PpWX9Nzcf: {
																y:
																	(componentViewport?.y || 0) +
																	100 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	38 +
																	0 +
																	72,
															},
															tAhy0cIZG: {
																y:
																	(componentViewport?.y || 0) +
																	50 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	0 +
																	38 +
																	0 +
																	72,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-18pf3ae-container"}
														layoutDependency={layoutDependency}
														layoutId={"VsUKITEhW-container"}
														nodeId={"VsUKITEhW"}
														rendersWithMotion={true}
														scopeId={"LT0gX9mtu"}
													>
														{_jsx(stdin_default, {
															aLnDlFZKR: resolvedLinks2[0],
															Cn6fz_Vow: "How it Works!",
															height: "100%",
															id: "VsUKITEhW",
															layoutId: "VsUKITEhW",
															TqaTpTiSx: false,
															variant: "vbxf8HL8_",
															width: "100%",
															X2yrtSssb: false,
															...addPropertyOverrides(
																{
																	PpWX9Nzcf: {
																		aLnDlFZKR: resolvedLinks2[1],
																	},
																	tAhy0cIZG: {
																		aLnDlFZKR: resolvedLinks2[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "iEYhqIzLi",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "iEYhqIzLi",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "iEYhqIzLi",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks3) => (
												<ComponentViewportProvider
													height={26}
													y={
														(componentViewport?.y || 0) +
														100 +
														0 +
														0 +
														0 +
														0 +
														38 +
														0 +
														108
													}
													{...addPropertyOverrides(
														{
															PpWX9Nzcf: {
																y:
																	(componentViewport?.y || 0) +
																	100 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	38 +
																	0 +
																	108,
															},
															tAhy0cIZG: {
																y:
																	(componentViewport?.y || 0) +
																	50 +
																	0 +
																	0 +
																	304 +
																	0 +
																	0 +
																	0 +
																	38 +
																	0 +
																	108,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-1hx2e9w-container"}
														layoutDependency={layoutDependency}
														layoutId={"CqH8G6mpL-container"}
														nodeId={"CqH8G6mpL"}
														rendersWithMotion={true}
														scopeId={"LT0gX9mtu"}
													>
														{_jsx(stdin_default, {
															aLnDlFZKR: resolvedLinks3[0],
															Cn6fz_Vow: "Contact",
															height: "100%",
															id: "CqH8G6mpL",
															layoutId: "CqH8G6mpL",
															TqaTpTiSx: false,
															variant: "vbxf8HL8_",
															width: "100%",
															X2yrtSssb: false,
															...addPropertyOverrides(
																{
																	PpWX9Nzcf: {
																		aLnDlFZKR: resolvedLinks3[1],
																	},
																	tAhy0cIZG: {
																		aLnDlFZKR: resolvedLinks3[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-8c1gx3"}
									data-framer-name={"Social"}
									layoutDependency={layoutDependency}
									layoutId={"SexQZEngr"}
								>
									<motion.div
										className={"framer-1j0014u"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"g23H6n5Iy"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-uizqdh"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"lJyUUZzVu"}
											style={{
												"--framer-paragraph-spacing": "0px",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.h4
													className={"framer-styles-preset-1ing3ma"}
													data-styles-preset={"VnmEZ_3BZ"}
												>
													{"Social"}
												</motion.h4>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-11pn9ct"}
										data-framer-name={"Bottom"}
										layoutDependency={layoutDependency}
										layoutId={"PUADRHOqo"}
									>
										<ComponentViewportProvider
											height={26}
											y={
												(componentViewport?.y || 0) +
												100 +
												0 +
												0 +
												0 +
												0 +
												38 +
												0 +
												0
											}
											{...addPropertyOverrides(
												{
													PpWX9Nzcf: {
														y:
															(componentViewport?.y || 0) +
															100 +
															0 +
															0 +
															304 +
															0 +
															0 +
															38 +
															0 +
															0,
													},
													tAhy0cIZG: {
														y:
															(componentViewport?.y || 0) +
															50 +
															0 +
															0 +
															304 +
															0 +
															222 +
															0 +
															38 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1f61qu3-container"}
												layoutDependency={layoutDependency}
												layoutId={"AWuMSWL_M-container"}
												nodeId={"AWuMSWL_M"}
												rendersWithMotion={true}
												scopeId={"LT0gX9mtu"}
											>
												{_jsx(stdin_default, {
													aLnDlFZKR: "https://x.com/MandroDesign",
													Cn6fz_Vow: "Twitter (X)",
													height: "100%",
													id: "AWuMSWL_M",
													layoutId: "AWuMSWL_M",
													TqaTpTiSx: true,
													variant: "vbxf8HL8_",
													width: "100%",
													X2yrtSssb: false,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={26}
											y={
												(componentViewport?.y || 0) +
												100 +
												0 +
												0 +
												0 +
												0 +
												38 +
												0 +
												36
											}
											{...addPropertyOverrides(
												{
													PpWX9Nzcf: {
														y:
															(componentViewport?.y || 0) +
															100 +
															0 +
															0 +
															304 +
															0 +
															0 +
															38 +
															0 +
															36,
													},
													tAhy0cIZG: {
														y:
															(componentViewport?.y || 0) +
															50 +
															0 +
															0 +
															304 +
															0 +
															222 +
															0 +
															38 +
															0 +
															36,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-igfsmi-container"}
												layoutDependency={layoutDependency}
												layoutId={"P3ptZiQuh-container"}
												nodeId={"P3ptZiQuh"}
												rendersWithMotion={true}
												scopeId={"LT0gX9mtu"}
											>
												{_jsx(stdin_default, {
													aLnDlFZKR: "https://www.instagram.com/",
													Cn6fz_Vow: "Instagram",
													height: "100%",
													id: "P3ptZiQuh",
													layoutId: "P3ptZiQuh",
													TqaTpTiSx: true,
													variant: "vbxf8HL8_",
													width: "100%",
													X2yrtSssb: false,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-1x9kfky"}
									data-framer-name={"About"}
									layoutDependency={layoutDependency}
									layoutId={"sxT18U1mz"}
								>
									<FormContainer
										className={"framer-p9blxb"}
										layoutDependency={layoutDependency}
										layoutId={"HLKgJIksA"}
										nodeId={"HLKgJIksA"}
									>
										{(formState) => <_Fragment />}
									</FormContainer>
								</motion.div>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-g1rbiy"}
							data-framer-name={"Bottom"}
							layoutDependency={layoutDependency}
							layoutId={"fyZQQHDs0"}
						>
							<motion.div
								className={"framer-u157m0"}
								data-framer-name={"Seperator"}
								layoutDependency={layoutDependency}
								layoutId={"vF95pkrWU"}
								style={{
									background:
										"linear-gradient(90.00000000000075deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.1) 50%, rgba(255, 255, 255, 0) 100%)",
								}}
							/>
							<motion.div
								className={"framer-1bzffsm"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"iYA90OaOU"}
							>
								<motion.div
									className={"framer-1dc31xf"}
									data-framer-name={"Left"}
									layoutDependency={layoutDependency}
									layoutId={"V33sNCVG4"}
								>
									<ComponentViewportProvider
										height={26}
										y={(componentViewport?.y || 0) + 100 + 344 + 0 + 25 + 0 + 0}
										{...addPropertyOverrides(
											{
												PpWX9Nzcf: {
													y:
														(componentViewport?.y || 0) +
														100 +
														566 +
														0 +
														25 +
														0 +
														0,
												},
												tAhy0cIZG: {
													y:
														(componentViewport?.y || 0) +
														50 +
														726 +
														0 +
														25 +
														0 +
														36 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1kjbmpx-container"}
											layoutDependency={layoutDependency}
											layoutId={"ZzU8PmB3m-container"}
											nodeId={"ZzU8PmB3m"}
											rendersWithMotion={true}
											scopeId={"LT0gX9mtu"}
										>
											{_jsx(stdin_default, {
												aLnDlFZKR: "https://x.com/MandroDesign",
												Cn6fz_Vow: "\xA9 2025 Reeva. All Rights Reserved.",
												height: "100%",
												id: "ZzU8PmB3m",
												layoutId: "ZzU8PmB3m",
												TqaTpTiSx: true,
												variant: "vbxf8HL8_",
												width: "100%",
												X2yrtSssb: false,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion.div>
								<motion.div
									className={"framer-1su39qg"}
									data-framer-name={"Right"}
									layoutDependency={layoutDependency}
									layoutId={"R9YYH6P9X"}
								>
									<motion.div
										className={"framer-1027xeg"}
										data-framer-name={"Left"}
										layoutDependency={layoutDependency}
										layoutId={"ijYFvhy3y"}
									>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "FsIlOVO8T",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "FsIlOVO8T",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "FsIlOVO8T",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks4) => (
												<ComponentViewportProvider
													height={26}
													y={
														(componentViewport?.y || 0) +
														100 +
														344 +
														0 +
														25 +
														0 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															PpWX9Nzcf: {
																y:
																	(componentViewport?.y || 0) +
																	100 +
																	566 +
																	0 +
																	25 +
																	0 +
																	0 +
																	0,
															},
															tAhy0cIZG: {
																y:
																	(componentViewport?.y || 0) +
																	50 +
																	726 +
																	0 +
																	25 +
																	0 +
																	0 +
																	0 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-fqk9co-container"}
														layoutDependency={layoutDependency}
														layoutId={"gJT8xVxZ0-container"}
														nodeId={"gJT8xVxZ0"}
														rendersWithMotion={true}
														scopeId={"LT0gX9mtu"}
													>
														{_jsx(stdin_default, {
															aLnDlFZKR: resolvedLinks4[0],
															Cn6fz_Vow: "Terms & Conditions",
															height: "100%",
															id: "gJT8xVxZ0",
															layoutId: "gJT8xVxZ0",
															TqaTpTiSx: false,
															variant: "vbxf8HL8_",
															width: "100%",
															X2yrtSssb: false,
															...addPropertyOverrides(
																{
																	PpWX9Nzcf: {
																		aLnDlFZKR: resolvedLinks4[1],
																	},
																	tAhy0cIZG: {
																		aLnDlFZKR: resolvedLinks4[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion.div>
									<motion.div
										className={"framer-m4fgmb"}
										data-framer-name={"Seperator"}
										layoutDependency={layoutDependency}
										layoutId={"pWD09mzkz"}
										style={{
											background:
												"linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0) 100%)",
										}}
									/>
									<motion.div
										className={"framer-1qhiyeb"}
										data-framer-name={"Right"}
										layoutDependency={layoutDependency}
										layoutId={"TvAeoEFLb"}
									>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "MiaczO6ls",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "MiaczO6ls",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "MiaczO6ls",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks5) => (
												<ComponentViewportProvider
													height={26}
													y={
														(componentViewport?.y || 0) +
														100 +
														344 +
														0 +
														25 +
														0 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															PpWX9Nzcf: {
																y:
																	(componentViewport?.y || 0) +
																	100 +
																	566 +
																	0 +
																	25 +
																	0 +
																	0 +
																	0,
															},
															tAhy0cIZG: {
																y:
																	(componentViewport?.y || 0) +
																	50 +
																	726 +
																	0 +
																	25 +
																	0 +
																	0 +
																	0 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-1mjax5b-container"}
														layoutDependency={layoutDependency}
														layoutId={"jNGVTUEnM-container"}
														nodeId={"jNGVTUEnM"}
														rendersWithMotion={true}
														scopeId={"LT0gX9mtu"}
													>
														{_jsx(stdin_default, {
															aLnDlFZKR: resolvedLinks5[0],
															Cn6fz_Vow: "Privacy Policy",
															height: "100%",
															id: "jNGVTUEnM",
															layoutId: "jNGVTUEnM",
															TqaTpTiSx: false,
															variant: "vbxf8HL8_",
															width: "100%",
															X2yrtSssb: false,
															...addPropertyOverrides(
																{
																	PpWX9Nzcf: {
																		aLnDlFZKR: resolvedLinks5[1],
																	},
																	tAhy0cIZG: {
																		aLnDlFZKR: resolvedLinks5[2],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TSZIr.framer-1ukbytl, .framer-TSZIr .framer-1ukbytl { display: block; }",
	".framer-TSZIr.framer-z20imy { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 90px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 100px 0px 24px 0px; position: relative; width: 1200px; }",
	".framer-TSZIr .framer-qluo01 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1360px; overflow: visible; padding: 0px 80px 0px 80px; position: relative; width: 100%; z-index: 2; }",
	".framer-TSZIr .framer-1njellx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: center; overflow: visible; padding: 0px 50px 0px 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-1xq6p9a { flex: none; height: 71px; overflow: hidden; position: relative; text-decoration: none; width: 176px; }",
	".framer-TSZIr .framer-mhuyew { flex: none; height: 1px; position: relative; width: 230px; }",
	".framer-TSZIr .framer-1xy8ipc { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 260px; }",
	".framer-TSZIr .framer-4s96la { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-TSZIr .framer-fnx7o9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-1jltczg, .framer-TSZIr .framer-8c1gx3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-wdq88k, .framer-TSZIr .framer-1j0014u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-1rl1jwu, .framer-TSZIr .framer-uizqdh { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-TSZIr .framer-pxkf8m, .framer-TSZIr .framer-11pn9ct { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-as62wa-container, .framer-TSZIr .framer-gketd9-container, .framer-TSZIr .framer-18pf3ae-container, .framer-TSZIr .framer-1hx2e9w-container, .framer-TSZIr .framer-1f61qu3-container, .framer-TSZIr .framer-igfsmi-container, .framer-TSZIr .framer-1kjbmpx-container, .framer-TSZIr .framer-fqk9co-container, .framer-TSZIr .framer-1mjax5b-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-TSZIr .framer-1x9kfky { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-p9blxb { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; min-height: 52px; min-width: 324px; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-g1rbiy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; max-width: 1440px; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-TSZIr .framer-u157m0 { flex: none; height: 1px; position: relative; width: 100%; }",
	".framer-TSZIr .framer-1bzffsm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 120px 0px 120px; position: relative; width: 100%; }",
	".framer-TSZIr .framer-1dc31xf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-1su39qg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-1027xeg, .framer-TSZIr .framer-1qhiyeb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-TSZIr .framer-m4fgmb { flex: none; height: 26px; position: relative; width: 1px; }",
	".framer-TSZIr.framer-v-5vmnq2.framer-z20imy { width: 810px; }",
	".framer-TSZIr.framer-v-5vmnq2 .framer-qluo01 { flex-direction: column; gap: 50px; justify-content: flex-start; padding: 0px 70px 0px 70px; }",
	".framer-TSZIr.framer-v-5vmnq2 .framer-fnx7o9 { gap: unset; justify-content: space-between; width: 100%; }",
	".framer-TSZIr.framer-v-5vmnq2 .framer-1bzffsm { padding: 0px 70px 0px 70px; }",
	".framer-TSZIr.framer-v-1mpq8ij.framer-z20imy { gap: 50px; padding: 50px 0px 24px 0px; width: 390px; }",
	".framer-TSZIr.framer-v-1mpq8ij .framer-qluo01 { flex-direction: column; gap: 50px; justify-content: flex-start; padding: 0px 30px 0px 30px; }",
	".framer-TSZIr.framer-v-1mpq8ij .framer-1njellx { width: 100%; }",
	".framer-TSZIr.framer-v-1mpq8ij .framer-1xy8ipc { max-width: 300px; width: 100%; }",
	".framer-TSZIr.framer-v-1mpq8ij .framer-fnx7o9 { flex-direction: column; gap: 50px; }",
	".framer-TSZIr.framer-v-1mpq8ij .framer-1bzffsm { flex-direction: column; gap: 10px; justify-content: flex-start; padding: 0px 30px 0px 30px; }",
	".framer-TSZIr.framer-v-1mpq8ij .framer-1dc31xf { order: 1; }",
	".framer-TSZIr.framer-v-1mpq8ij .framer-1su39qg { order: 0; }",
	...css,
	...css2,
	'.framer-TSZIr[data-border="true"]::after, .framer-TSZIr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerLT0gX9mtu = withCSS(Component, css3, "framer-TSZIr");
var stdin_default2 = FramerLT0gX9mtu;
FramerLT0gX9mtu.displayName = "Navigation/Footer";
FramerLT0gX9mtu.defaultProps = {
	height: 467,
	width: 1200,
};
addPropertyControls(FramerLT0gX9mtu, {
	variant: {
		options: ["hDiagrBhX", "PpWX9Nzcf", "tAhy0cIZG"],
		optionTitles: ["L", "M", "S"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerLT0gX9mtu,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...NavigationTextHoverFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation/footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "tAhy0cIZG",
	md: "PpWX9Nzcf",
	xl: "hDiagrBhX",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
