// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary ' | 'Secondary' // Variant
 * point1?: string // Point 1
 * point2?: string // Point 2
 * point3?: string // Point 3
 * point4?: string // Point 4
}} Props

 */
import { stdin_default } from "./chunks/chunk-O7YVACLF.js";
import "./chunks/chunk-KEXS3RZD.js";
import "./chunks/chunk-5FLMVJY2.js";
import "./chunks/chunk-JOQ27WRR.js";
import { routes } from "./chunks/chunk-XIXCBJDO.js";

// virtual:comparison-card
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "Q_AjASQuJ",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ComparisonCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var comparison_card_default = ComponentWithRoot;
export { comparison_card_default as default };
