// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M' | 'S' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-BQ3M46CP.js";
import "./chunks/chunk-IUHXWZTF.js";
import "./chunks/chunk-5ZAP26CV.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-WEQDPRX4.js";
import { className, css, fonts } from "./chunks/chunk-6RBWXANE.js";
import { stdin_default } from "./chunks/chunk-JQY6WALF.js";
import "./chunks/chunk-JOQ27WRR.js";
import "./chunks/chunk-IXDMRUES.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-XIXCBJDO.js";

// virtual:faq-about-me
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/51wwD6jLtE16iO4hrSpl/XzaMdvuOONQJ9DEjt67b/b5SJ7bkwz.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var TagPrimaryTagFonts = getFonts(stdin_default);
var FAQFAQFonts = getFonts(stdin_default2);
var cycleOrder = ["CIlLf4V3d", "nGfG0EdUe", "X6KtK0AAO"];
var serializationHash = "framer-WPICI";
var variantClassNames = {
	CIlLf4V3d: "framer-v-tryr41",
	nGfG0EdUe: "framer-v-visa2q",
	X6KtK0AAO: "framer-v-1ufmvkk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	filter: "blur(10px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	damping: 50,
	delay: 0.05,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var textEffect = {
	effect: animation,
	repeat: false,
	startDelay: 0,
	threshold: 0.5,
	tokenization: "word",
	transition: transition2,
	trigger: "onInView",
	type: "appear",
};
var textEffect1 = {
	effect: animation,
	repeat: false,
	startDelay: 0.2,
	threshold: 0.5,
	tokenization: "word",
	transition: transition2,
	trigger: "onInView",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	L: "CIlLf4V3d",
	M: "nGfG0EdUe",
	S: "X6KtK0AAO",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "CIlLf4V3d",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CIlLf4V3d",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-tryr41",
							className3,
							classNames,
						)}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"CIlLf4V3d"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-8e9f7de0-9fd7-44d3-bc3e-2dea20c4e4bd, rgb(0, 0, 0))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								nGfG0EdUe: {
									"data-framer-name": "M",
								},
								X6KtK0AAO: {
									"data-framer-name": "S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "Rays",
								fit: "fill",
								intrinsicHeight: 779,
								intrinsicWidth: 1199,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 1558,
								pixelWidth: 2398,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/HQiQT243MN1itZOX771FxR6euwI.png?scale-down-to=2048&width=2398&height=1558",
								srcSet:
									"https://framerusercontent.com/images/HQiQT243MN1itZOX771FxR6euwI.png?scale-down-to=512&width=2398&height=1558 512w,https://framerusercontent.com/images/HQiQT243MN1itZOX771FxR6euwI.png?scale-down-to=1024&width=2398&height=1558 1024w,https://framerusercontent.com/images/HQiQT243MN1itZOX771FxR6euwI.png?scale-down-to=2048&width=2398&height=1558 2048w,https://framerusercontent.com/images/HQiQT243MN1itZOX771FxR6euwI.png?width=2398&height=1558 2398w",
							}}
							className={"framer-1xzosjh"}
							data-framer-name={"Light Rays"}
							layoutDependency={layoutDependency}
							layoutId={"ZpT3STvta"}
							style={{
								opacity: 0.7,
							}}
						/>
						<motion.div
							className={"framer-tdwgiu"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"FK7FGXOJX"}
						>
							<motion.div
								className={"framer-3iu0g3"}
								data-framer-name={"Left"}
								layoutDependency={layoutDependency}
								layoutId={"ClOo6EbT0"}
							>
								<motion.div
									className={"framer-fvuhpk"}
									data-framer-name={"Content"}
									layoutDependency={layoutDependency}
									layoutId={"Y1JESJPsr"}
								>
									<motion.div
										className={"framer-148tp01"}
										data-framer-name={"Top"}
										layoutDependency={layoutDependency}
										layoutId={"ojbomXuoO"}
									>
										<ComponentViewportProvider
											height={40}
											y={
												(componentViewport?.y || 0) +
												100 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides(
												{
													nGfG0EdUe: {
														y:
															(componentViewport?.y || 0) +
															100 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0,
													},
													X6KtK0AAO: {
														y:
															(componentViewport?.y || 0) +
															80 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1mqiwau-container"}
												layoutDependency={layoutDependency}
												layoutId={"Xy1tyERKy-container"}
												nodeId={"Xy1tyERKy"}
												rendersWithMotion={true}
												scopeId={"b5SJ7bkwz"}
											>
												{_jsx(stdin_default, {
													aZ7GvMqIl: "Question",
													height: "100%",
													id: "Xy1tyERKy",
													KS7KLFqN8: "FAQ",
													layoutId: "Xy1tyERKy",
													rQKAY6456: "NEW",
													variant: "axDSKQZXP",
													width: "100%",
													xAPRy8bad: 0,
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<motion.div
											className={"framer-iwucs8"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"MRrrFedoV"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-tg2ytc"}
												data-framer-name={"Text 1"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"GhfVm6JbA"}
												style={{
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-190xti5"}
														data-styles-preset={"QuTNz53Yy"}
													>
														{"Frequently"}
													</motion.h2>
												</React.Fragment>
											</RichText>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-127qkvb"}
												data-framer-name={"Text 2"}
												effect={textEffect1}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"t3cuqjGih"}
												style={{
													"--extracted-1of0zx5":
														"var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6))",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h2
														className={"framer-styles-preset-190xti5"}
														data-styles-preset={"QuTNz53Yy"}
														style={{
															"--framer-text-color":
																"var(--extracted-1of0zx5, var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6)))",
														}}
													>
														{"Asked Questions"}
													</motion.h2>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-ou3f88"}
										data-framer-name={"Bottom"}
										layoutDependency={layoutDependency}
										layoutId={"f5PIt7YUE"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1alau9g"}
											data-framer-name={"Body Text"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"kKwgvqOh4"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											variants={{
												X6KtK0AAO: {
													"--extracted-r6o4lv":
														"var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													X6KtK0AAO: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-x0s9r5"}
																	data-styles-preset={"QhK6qqT5U"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6)))",
																	}}
																>
																	{
																		"Effortlessly connect with your favorite tools. Whether it's your CRM, email marketing platform."
																	}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-x0s9r5"}
													data-styles-preset={"QhK6qqT5U"}
												>
													{
														"Have questions? Our FAQ section has you covered with "
													}
													<motion.br />
													{"quick answers to the most common inquiries."}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							</motion.div>
							<ComponentViewportProvider
								height={531}
								width={`min(max((min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 60px) / 2, 1px), 700px)`}
								y={(componentViewport?.y || 0) + 100 + 0 + 0}
								{...addPropertyOverrides(
									{
										nGfG0EdUe: {
											width: `min(${componentViewport?.width || "100vw"} - 100px, 1200px)`,
											y: (componentViewport?.y || 0) + 100 + 0 + 0 + 400,
										},
										X6KtK0AAO: {
											width: `min(${componentViewport?.width || "100vw"} - 60px, 1200px)`,
											y: (componentViewport?.y || 0) + 80 + 0 + 0 + 373,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-1b4lort-container"}
									layoutDependency={layoutDependency}
									layoutId={"zbMRcH7jH-container"}
									nodeId={"zbMRcH7jH"}
									rendersWithMotion={true}
									scopeId={"b5SJ7bkwz"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "zbMRcH7jH",
										layoutId: "zbMRcH7jH",
										style: {
											maxWidth: "100%",
											width: "100%",
										},
										width: "100%",
										...addPropertyOverrides(
											{
												nGfG0EdUe: {
													style: {
														width: "100%",
													},
												},
												X6KtK0AAO: {
													style: {
														width: "100%",
													},
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WPICI.framer-1e1bkfr, .framer-WPICI .framer-1e1bkfr { display: block; }",
	".framer-WPICI.framer-tryr41 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 100px; height: min-content; justify-content: flex-start; max-width: 1480px; overflow: hidden; padding: 100px 80px 0px 80px; position: relative; width: 1200px; }",
	".framer-WPICI .framer-1xzosjh { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-WPICI .framer-tdwgiu { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-WPICI .framer-3iu0g3 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: center; max-width: 450px; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-WPICI .framer-fvuhpk { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-WPICI .framer-148tp01 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-WPICI .framer-1mqiwau-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-WPICI .framer-iwucs8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-WPICI .framer-tg2ytc, .framer-WPICI .framer-127qkvb { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-WPICI .framer-ou3f88 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 450px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-WPICI .framer-1alau9g { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-WPICI .framer-1b4lort-container { flex: 1 0 0px; height: auto; max-width: 700px; position: relative; width: 1px; z-index: 1; }",
	".framer-WPICI.framer-v-visa2q.framer-tryr41 { padding: 100px 50px 0px 50px; width: 810px; }",
	".framer-WPICI.framer-v-visa2q .framer-tdwgiu { flex-direction: column; }",
	".framer-WPICI.framer-v-visa2q .framer-3iu0g3 { flex: none; order: 0; width: 100%; }",
	".framer-WPICI.framer-v-visa2q .framer-1b4lort-container, .framer-WPICI.framer-v-1ufmvkk .framer-1b4lort-container { flex: none; max-width: unset; order: 1; width: 100%; }",
	".framer-WPICI.framer-v-1ufmvkk.framer-tryr41 { gap: 80px; padding: 80px 30px 0px 30px; width: 390px; }",
	".framer-WPICI.framer-v-1ufmvkk .framer-tdwgiu { flex-direction: column; gap: 40px; }",
	".framer-WPICI.framer-v-1ufmvkk .framer-3iu0g3 { flex: none; max-width: 460px; order: 0; width: 100%; }",
	".framer-WPICI.framer-v-1ufmvkk .framer-iwucs8 { gap: 3px; }",
	...css2,
	...css,
];
var Framerb5SJ7bkwz = withCSS(Component, css3, "framer-WPICI");
var stdin_default3 = Framerb5SJ7bkwz;
Framerb5SJ7bkwz.displayName = "FAQ-AboutMe";
Framerb5SJ7bkwz.defaultProps = {
	height: 626,
	width: 1200,
};
addPropertyControls(Framerb5SJ7bkwz, {
	variant: {
		options: ["CIlLf4V3d", "nGfG0EdUe", "X6KtK0AAO"],
		optionTitles: ["L", "M", "S"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	Framerb5SJ7bkwz,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagPrimaryTagFonts,
		...FAQFAQFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-about-me
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "X6KtK0AAO",
	md: "nGfG0EdUe",
	xl: "CIlLf4V3d",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqAboutMeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var faq_about_me_default = ComponentWithRoot;
export { faq_about_me_default as default };
