// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M' | 'S' // Variant
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-6TKPDYMZ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KOW5QF4M.js";
import { className, css, fonts } from "./chunks/chunk-6RBWXANE.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-JQY6WALF.js";
import "./chunks/chunk-IXDMRUES.js";
import "./chunks/chunk-BVM6H744.js";
import { stdin_default } from "./chunks/chunk-6S67OR3F.js";
import "./chunks/chunk-ZGMLUSG3.js";
import { routes } from "./chunks/chunk-XIXCBJDO.js";

// virtual:hero-contact
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Mf8M913IRrvuJZgkF1lg/uz3sR5mKWVzNPMpSCGWh/VcycPnV9B.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	FormPlainTextInput,
	FormSelect,
	getFonts,
	getFontsFromSharedStyle,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/1waYm9wHQs4eSAg5onxn/VSagO50ZEFgc1T8iBGYc/JQSP3EtUD.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;DM Sans-500",
	"GF;DM Sans-700",
	"GF;DM Sans-700italic",
	"GF;DM Sans-500italic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
				weight: "500",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwARZthS2f3ZGMZpg.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat9uCm32RmYJpso5.woff2",
				weight: "700",
			},
			{
				family: "DM Sans",
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/dmsans/v15/rP2rp2ywxg089UriCZaSExd86J3t9jz86Mvy4qCRAL19DksVat-7DW32RmYJpso5.woff2",
				weight: "500",
			},
		],
	},
];
var css3 = [
	'.framer-QLHYT .framer-styles-preset-1gjbdzu:not(.rich-text-wrapper), .framer-QLHYT .framer-styles-preset-1gjbdzu.rich-text-wrapper p { --framer-font-family: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-family-italic: "DM Sans", "DM Sans Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.5px; --framer-line-height: 26px; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, #ffffff); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className3 = "framer-QLHYT";

// /:https://framerusercontent.com/modules/Mf8M913IRrvuJZgkF1lg/uz3sR5mKWVzNPMpSCGWh/VcycPnV9B.js
var TagPrimaryTagFonts = getFonts(stdin_default2);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var ButtonPrimaryButtonFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var ButtonContactButtonFonts = getFonts(stdin_default3);
var cycleOrder = ["O_PbKerS_", "XP32tdAQ6", "g2hNi2hXF"];
var serializationHash = "framer-DHik3";
var variantClassNames = {
	g2hNi2hXF: "framer-v-1pgqt8g",
	O_PbKerS_: "framer-v-1bjp701",
	XP32tdAQ6: "framer-v-75r16k",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	damping: 60,
	delay: 0.5,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var transition4 = {
	damping: 60,
	delay: 0.7,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var animation4 = {
	filter: "blur(10px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition5 = {
	damping: 50,
	delay: 0.05,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var textEffect = {
	effect: animation4,
	repeat: false,
	startDelay: 0.9,
	tokenization: "word",
	transition: transition5,
	trigger: "onMount",
	type: "appear",
};
var transition6 = {
	damping: 60,
	delay: 1.1,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition6,
	x: 0,
	y: 0,
};
var transition7 = {
	damping: 60,
	delay: 1,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation6 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition7,
	x: 0,
	y: 0,
};
var formVariants = (form, variants, currentVariant) => {
	switch (form.state) {
		case "success":
			return variants.success ?? currentVariant;
		case "pending":
			return variants.pending ?? currentVariant;
		case "error":
			return variants.error ?? currentVariant;
		case "incomplete":
			return variants.incomplete ?? currentVariant;
	}
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	L: "O_PbKerS_",
	M: "XP32tdAQ6",
	S: "g2hNi2hXF",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "O_PbKerS_",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "O_PbKerS_",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1bjp701",
							className4,
							classNames,
						)}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"O_PbKerS_"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								g2hNi2hXF: {
									"data-framer-name": "S",
								},
								XP32tdAQ6: {
									"data-framer-name": "M",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1tkruiv"}
							data-framer-name={"Spacer"}
							layoutDependency={layoutDependency}
							layoutId={"xoSewhEic"}
						/>
						<motion.div
							className={"framer-acqazr"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"veimrRvXr"}
							style={{
								background:
									"radial-gradient(60% 88% at 50% 64.2%, var(--token-f951c3a8-aa43-4825-aa75-915aa92c20d1, rgb(79, 26, 214)) 0%, rgb(114, 59, 255) 39.99155405405405%, var(--token-123b0380-d5c1-475a-b484-6e62cac5babe, rgb(25, 13, 46)) 84.93278434684684%, rgb(0, 0, 0) 100%)",
							}}
						>
							<motion.div
								className={"framer-117r0ss"}
								data-framer-name={"Particles "}
								layoutDependency={layoutDependency}
								layoutId={"dq2T2K8aQ"}
							>
								<motion.div
									className={"framer-r52apt"}
									data-framer-name={"Vignette"}
									layoutDependency={layoutDependency}
									layoutId={"Fqdmxvl0E"}
									style={{
										background:
											"radial-gradient(54% 50% at 50% 57.199999999999996%, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.67) 64.51471002252252%, rgb(0, 0, 0) 100%)",
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-1cmchmt"}
								data-framer-name={"Gradient Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"uuSemXU3O"}
								style={{
									background:
										"linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, rgb(0, 0, 0) 100%)",
								}}
							/>
							<motion.div
								className={"framer-14aeo17"}
								data-framer-name={"Top"}
								layoutDependency={layoutDependency}
								layoutId={"vcDjwG3oR"}
							>
								<motion.div
									className={"framer-19sish5"}
									data-framer-name={"Text/Tag"}
									layoutDependency={layoutDependency}
									layoutId={"yjkBEsPGl"}
								>
									<motion.div
										className={"framer-1676zb2"}
										data-framer-name={"Tag & Title"}
										layoutDependency={layoutDependency}
										layoutId={"dBYgxf2VN"}
									>
										<ComponentViewportProvider height={40}>
											<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation}
												className={"framer-v0gqac-container"}
												data-framer-appear-id={"v0gqac"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"jZqPPP3kl-container"}
												nodeId={"jZqPPP3kl"}
												optimized={true}
												rendersWithMotion={true}
												scopeId={"VcycPnV9B"}
											>
												{_jsx(stdin_default2, {
													aZ7GvMqIl: "Acorn",
													height: "100%",
													id: "jZqPPP3kl",
													KS7KLFqN8: "Collaborate With Us",
													layoutId: "jZqPPP3kl",
													rQKAY6456: "24/7",
													variant: "AksRoqhcS",
													width: "100%",
													xAPRy8bad: 0,
												})}
											</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
										</ComponentViewportProvider>
										<motion.div
											className={"framer-cw5ibw"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"NE5_hnSg3"}
										>
											<RichTextWithFXWithOptimizedAppearEffect
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation2}
												className={"framer-ngp4ar"}
												data-framer-appear-id={"ngp4ar"}
												data-framer-name={"Text 1"}
												fonts={["Inter"]}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"AJQ4ozowv"}
												optimized={true}
												style={{
													"--extracted-gdpscs": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														g2hNi2hXF: {
															children: (
																<React.Fragment>
																	<motion.h1
																		className={"framer-styles-preset-1idioqq"}
																		data-styles-preset={"ABKs9wxVy"}
																		style={{
																			"--framer-text-alignment": "left",
																			"--framer-text-color":
																				"var(--extracted-gdpscs, rgb(255, 255, 255))",
																		}}
																	>
																		<motion.span
																			data-text-fill={"true"}
																			style={{
																				backgroundImage:
																					"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
																			}}
																		>
																			{"Any Questions Rising? We are All Here."}
																		</motion.span>
																	</motion.h1>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.h1
														className={"framer-styles-preset-1idioqq"}
														data-styles-preset={"ABKs9wxVy"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
															}}
														>
															{"Have Any Doubts? We"}
														</motion.span>
													</motion.h1>
												</React.Fragment>
											</RichTextWithFXWithOptimizedAppearEffect>
											<RichTextWithFXWithOptimizedAppearEffect
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation3}
												className={"framer-13ympta"}
												data-framer-appear-id={"13ympta"}
												data-framer-name={"Text 2"}
												fonts={["Inter"]}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"RwwhjGKQM"}
												optimized={true}
												style={{
													"--extracted-gdpscs": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														g2hNi2hXF: {
															children: (
																<React.Fragment>
																	<motion.h1
																		className={"framer-styles-preset-1idioqq"}
																		data-styles-preset={"ABKs9wxVy"}
																		style={{
																			"--framer-text-alignment": "left",
																			"--framer-text-color":
																				"var(--extracted-gdpscs, rgb(255, 255, 255))",
																		}}
																	>
																		<motion.span
																			data-text-fill={"true"}
																			style={{
																				backgroundImage:
																					"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
																			}}
																		>
																			{"are Ready to Help."}
																		</motion.span>
																	</motion.h1>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.h1
														className={"framer-styles-preset-1idioqq"}
														data-styles-preset={"ABKs9wxVy"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
															}}
														>
															{"are Ready to Help."}
														</motion.span>
													</motion.h1>
												</React.Fragment>
											</RichTextWithFXWithOptimizedAppearEffect>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-1mouatl"}
										data-framer-name={"Body"}
										layoutDependency={layoutDependency}
										layoutId={"EjwOlQtUs"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-15exkix"}
											data-framer-name={"Text"}
											effect={textEffect}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"XskWxu9c8"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											variants={{
												g2hNi2hXF: {
													"--extracted-r6o4lv":
														"var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													g2hNi2hXF: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-x0s9r5"}
																	data-styles-preset={"QhK6qqT5U"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6)))",
																	}}
																>
																	{
																		"Whether you have a question, need assistance, or want to start a new project, our team is here to help."
																	}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-x0s9r5"}
													data-styles-preset={"QhK6qqT5U"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{"Whether you need guidance, support, "}
													<motion.br />
													{"or a fresh start, our team is ready to assist you."}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation5}
									className={"framer-rkm0zu"}
									data-framer-appear-id={"rkm0zu"}
									data-framer-name={"Buttons"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"Se3nnsU6o"}
									optimized={true}
								>
									<ResolveLinks
										links={[
											{
												href: {
													hash: ":citGtIofE",
													webPageId: "iEYhqIzLi",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":citGtIofE",
													webPageId: "iEYhqIzLi",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													hash: ":citGtIofE",
													webPageId: "iEYhqIzLi",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider height={46}>
												<SmartComponentScopedContainer
													className={"framer-14ttus3-container"}
													layoutDependency={layoutDependency}
													layoutId={"S_HmmtRlN-container"}
													nodeId={"S_HmmtRlN"}
													rendersWithMotion={true}
													scopeId={"VcycPnV9B"}
												>
													{_jsx(stdin_default, {
														AL_NU982V: false,
														dlVBgpKLv: "Fill The Form Out!",
														GT109pdEG: resolvedLinks[0],
														height: "100%",
														id: "S_HmmtRlN",
														layoutId: "S_HmmtRlN",
														SD1BGlGhK: true,
														variant: "vf6JWDf13",
														width: "100%",
														YVFZiszrG: {
															borderColor:
																"var(--token-a58752c8-168c-47db-857e-906f22f33790, rgba(255, 255, 255, 0.15))",
															borderStyle: "solid",
															borderWidth: 3,
														},
														...addPropertyOverrides(
															{
																g2hNi2hXF: {
																	GT109pdEG: resolvedLinks[2],
																},
																XP32tdAQ6: {
																	GT109pdEG: resolvedLinks[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</MotionDivWithFXWithOptimizedAppearEffect>
							</motion.div>
							<MotionDivWithFXWithOptimizedAppearEffect
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation6}
								className={"framer-4t83n5"}
								data-framer-appear-id={"4t83n5"}
								data-framer-name={"Bottom"}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"citGtIofE"}
								optimized={true}
							>
								<motion.div
									className={"framer-1lqmbnu"}
									data-border={true}
									data-framer-name={"Form"}
									layoutDependency={layoutDependency}
									layoutId={"nP0DhMFo1"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-a9883d9b-c1bd-4bd9-be15-284cd72e1b1f, rgba(255, 255, 255, 0.07))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										backgroundColor:
											"var(--token-74f48371-76c0-476a-a319-1331b3a438c2, rgb(8, 8, 8))",
										borderBottomLeftRadius: 30,
										borderBottomRightRadius: 30,
										borderTopLeftRadius: 30,
										borderTopRightRadius: 30,
										boxShadow:
											"0px -19px 70px 0px rgba(79, 26, 214, 0.4), 0px -0.7961918735236395px 3.9809593676181976px 0px rgba(79, 26, 214, 0.02), 0px -2.414506143104518px 12.07253071552259px 0px rgba(79, 26, 214, 0.05), 0px -6.382653521484461px 31.91326760742231px 0px rgba(79, 26, 214, 0.13), 0px -20px 100px 0px rgba(79, 26, 214, 0.4)",
									}}
								>
									<motion.div
										className={"framer-a4nmtn"}
										data-border={true}
										data-framer-name={"Border"}
										layoutDependency={layoutDependency}
										layoutId={"x2tCE5vLN"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-082d630a-c036-4f77-8c8d-5d7b4650e064, rgba(255, 255, 255, 0.08))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											borderBottomLeftRadius: 22,
											borderBottomRightRadius: 22,
											borderTopLeftRadius: 22,
											borderTopRightRadius: 22,
										}}
									>
										<motion.div
											className={"framer-1uvffyy"}
											data-framer-name={"Content"}
											layoutDependency={layoutDependency}
											layoutId={"qoZVqk6yT"}
											style={{
												borderBottomLeftRadius: 21,
												borderBottomRightRadius: 21,
												borderTopLeftRadius: 21,
												borderTopRightRadius: 21,
											}}
										>
											<FormContainer
												action={
													"https://api.framer.com/forms/v1/forms/f6830bdf-8547-425f-bff2-716141371710/submit"
												}
												className={"framer-65elbn"}
												layoutDependency={layoutDependency}
												layoutId={"JVm6QINt6"}
												nodeId={"JVm6QINt6"}
											>
												{(formState) => (
													<_Fragment>
														<motion.div
															className={"framer-hh95lm"}
															data-framer-name={"First Name + Last Name"}
															layoutDependency={layoutDependency}
															layoutId={"gNfwstFTY"}
														>
															<motion.label
																className={"framer-1yox3eu"}
																data-framer-name={"First Name"}
																layoutDependency={layoutDependency}
																layoutId={"EZ9pyxPbE"}
															>
																<RichText
																	__fromCanvasComponent={true}
																	className={"framer-n7zn46"}
																	data-framer-name={"Text"}
																	fonts={["Inter"]}
																	layoutDependency={layoutDependency}
																	layoutId={"VwjgKc4uC"}
																	verticalAlignment={"top"}
																	withExternalLayout={true}
																>
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-1gjbdzu"}
																			data-styles-preset={"JQSP3EtUD"}
																		>
																			{"First name*"}
																		</motion.p>
																	</React.Fragment>
																</RichText>
																<FormPlainTextInput
																	className={"framer-1ivn5ez"}
																	inputName={"Name"}
																	layoutDependency={layoutDependency}
																	layoutId={"HYnwyqmQw"}
																	placeholder={"Jane"}
																	required={true}
																	style={{
																		"--framer-input-background":
																			"var(--token-cd35caec-4f2a-4f7e-8c70-9992720e55b3, rgba(51, 51, 51, 0.2))",
																		"--framer-input-border-bottom-width": "1px",
																		"--framer-input-border-color":
																			"var(--token-30ee69d1-cae6-4a5c-9af2-db5c94a12e77, rgba(255, 255, 255, 0.05))",
																		"--framer-input-border-left-width": "1px",
																		"--framer-input-border-radius-bottom-left":
																			"5px",
																		"--framer-input-border-radius-bottom-right":
																			"5px",
																		"--framer-input-border-radius-top-left":
																			"5px",
																		"--framer-input-border-radius-top-right":
																			"5px",
																		"--framer-input-border-right-width": "1px",
																		"--framer-input-border-style": "solid",
																		"--framer-input-border-top-width": "1px",
																		"--framer-input-font-color":
																			"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
																		"--framer-input-icon-color":
																			"rgb(153, 153, 153)",
																		"--framer-input-placeholder-color":
																			"var(--token-3f9a2c63-f1d1-4706-bf6c-31956c981af9, rgb(153, 153, 153))",
																	}}
																	type={"text"}
																/>
															</motion.label>
															<motion.label
																className={"framer-k3o1go"}
																data-framer-name={"Last Name"}
																layoutDependency={layoutDependency}
																layoutId={"lr8HgPo2W"}
															>
																<RichText
																	__fromCanvasComponent={true}
																	className={"framer-1woa6ie"}
																	data-framer-name={"Text"}
																	fonts={["Inter"]}
																	layoutDependency={layoutDependency}
																	layoutId={"rhYjatF1K"}
																	verticalAlignment={"top"}
																	withExternalLayout={true}
																>
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-1gjbdzu"}
																			data-styles-preset={"JQSP3EtUD"}
																		>
																			{"Last Name*"}
																		</motion.p>
																	</React.Fragment>
																</RichText>
																<FormPlainTextInput
																	className={"framer-p3yxdp"}
																	inputName={"Name"}
																	layoutDependency={layoutDependency}
																	layoutId={"Oe1c3_Iod"}
																	placeholder={"Smith"}
																	required={true}
																	style={{
																		"--framer-input-background":
																			"var(--token-cd35caec-4f2a-4f7e-8c70-9992720e55b3, rgba(51, 51, 51, 0.2))",
																		"--framer-input-border-bottom-width": "1px",
																		"--framer-input-border-color":
																			"var(--token-30ee69d1-cae6-4a5c-9af2-db5c94a12e77, rgba(255, 255, 255, 0.05))",
																		"--framer-input-border-left-width": "1px",
																		"--framer-input-border-radius-bottom-left":
																			"5px",
																		"--framer-input-border-radius-bottom-right":
																			"5px",
																		"--framer-input-border-radius-top-left":
																			"5px",
																		"--framer-input-border-radius-top-right":
																			"5px",
																		"--framer-input-border-right-width": "1px",
																		"--framer-input-border-style": "solid",
																		"--framer-input-border-top-width": "1px",
																		"--framer-input-font-color":
																			"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
																		"--framer-input-icon-color":
																			"rgb(153, 153, 153)",
																		"--framer-input-placeholder-color":
																			"var(--token-3f9a2c63-f1d1-4706-bf6c-31956c981af9, rgb(153, 153, 153))",
																	}}
																	type={"text"}
																/>
															</motion.label>
														</motion.div>
														<motion.label
															className={"framer-1e8vvoz"}
															data-framer-name={"Email"}
															layoutDependency={layoutDependency}
															layoutId={"Gxo7wSKaG"}
														>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-cle1l4"}
																data-framer-name={"Text"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"PpAYcOkfG"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1gjbdzu"}
																		data-styles-preset={"JQSP3EtUD"}
																	>
																		{"How can we reach you?*"}
																	</motion.p>
																</React.Fragment>
															</RichText>
															<FormPlainTextInput
																className={"framer-1qk866z"}
																inputName={"Email"}
																layoutDependency={layoutDependency}
																layoutId={"H1TuyAn5S"}
																placeholder={"jane@framer.com"}
																required={true}
																style={{
																	"--framer-input-background":
																		"var(--token-cd35caec-4f2a-4f7e-8c70-9992720e55b3, rgba(51, 51, 51, 0.2))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-30ee69d1-cae6-4a5c-9af2-db5c94a12e77, rgba(255, 255, 255, 0.05))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"5px",
																	"--framer-input-border-radius-bottom-right":
																		"5px",
																	"--framer-input-border-radius-top-left":
																		"5px",
																	"--framer-input-border-radius-top-right":
																		"5px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-font-color":
																		"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
																	"--framer-input-icon-color":
																		"rgb(153, 153, 153)",
																	"--framer-input-placeholder-color":
																		"var(--token-3f9a2c63-f1d1-4706-bf6c-31956c981af9, rgb(153, 153, 153))",
																}}
																type={"email"}
															/>
														</motion.label>
														<motion.div
															className={"framer-5ux4en"}
															data-framer-name={"Location + Category"}
															layoutDependency={layoutDependency}
															layoutId={"ebGWMjMVP"}
														>
															<motion.label
																className={"framer-1fggqtg"}
																data-framer-name={"Location"}
																layoutDependency={layoutDependency}
																layoutId={"b54jHJmNL"}
															>
																<RichText
																	__fromCanvasComponent={true}
																	className={"framer-qj37es"}
																	data-framer-name={"Text"}
																	fonts={["Inter"]}
																	layoutDependency={layoutDependency}
																	layoutId={"cciBONhsa"}
																	verticalAlignment={"top"}
																	withExternalLayout={true}
																>
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-1gjbdzu"}
																			data-styles-preset={"JQSP3EtUD"}
																		>
																			{"Where Are you from?*"}
																		</motion.p>
																	</React.Fragment>
																</RichText>
																<FormSelect
																	className={"framer-1tjjjiy"}
																	defaultValue={""}
																	inputName={"Location"}
																	layoutDependency={layoutDependency}
																	layoutId={"E4N3Cp2sZ"}
																	required={true}
																	selectOptions={[
																		{
																			disabled: true,
																			title: "Select your country\u2026",
																			type: "option",
																			value: "",
																		},
																		{
																			title: "Amsterdam",
																			type: "option",
																			value: "amsterdam",
																		},
																		{
																			title: "Barcelona",
																			type: "option",
																			value: "barcelona",
																		},
																	]}
																	style={{
																		"--framer-input-background":
																			"var(--token-cd35caec-4f2a-4f7e-8c70-9992720e55b3, rgba(51, 51, 51, 0.2))",
																		"--framer-input-border-bottom-width": "1px",
																		"--framer-input-border-color":
																			"var(--token-30ee69d1-cae6-4a5c-9af2-db5c94a12e77, rgba(255, 255, 255, 0.05))",
																		"--framer-input-border-left-width": "1px",
																		"--framer-input-border-radius-bottom-left":
																			"5px",
																		"--framer-input-border-radius-bottom-right":
																			"5px",
																		"--framer-input-border-radius-top-left":
																			"5px",
																		"--framer-input-border-radius-top-right":
																			"5px",
																		"--framer-input-border-right-width": "1px",
																		"--framer-input-border-style": "solid",
																		"--framer-input-border-top-width": "1px",
																		"--framer-input-font-color":
																			"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
																		"--framer-input-icon-color":
																			"rgb(153, 153, 153)",
																		"--framer-input-invalid-text-color":
																			"var(--token-3f9a2c63-f1d1-4706-bf6c-31956c981af9, rgb(153, 153, 153))",
																	}}
																/>
															</motion.label>
															<motion.label
																className={"framer-olgzgc"}
																data-framer-name={"Category"}
																layoutDependency={layoutDependency}
																layoutId={"o6I0D3bSY"}
															>
																<RichText
																	__fromCanvasComponent={true}
																	className={"framer-1nroqcl"}
																	data-framer-name={"Text"}
																	fonts={["Inter"]}
																	layoutDependency={layoutDependency}
																	layoutId={"I275lKMbw"}
																	verticalAlignment={"top"}
																	withExternalLayout={true}
																>
																	<React.Fragment>
																		<motion.p
																			className={"framer-styles-preset-1gjbdzu"}
																			data-styles-preset={"JQSP3EtUD"}
																		>
																			{"What's the type of your company?*"}
																		</motion.p>
																	</React.Fragment>
																</RichText>
																<FormSelect
																	className={"framer-138kdiq"}
																	defaultValue={""}
																	inputName={"Location"}
																	layoutDependency={layoutDependency}
																	layoutId={"rKYzxWoyc"}
																	required={true}
																	selectOptions={[
																		{
																			disabled: true,
																			title: "Select category",
																			type: "option",
																			value: "",
																		},
																		{
																			title: "Agency",
																			type: "option",
																			value: "Agency",
																		},
																		{
																			title: "SAAS",
																			type: "option",
																			value: "SAAS",
																		},
																		{
																			title: "Banking",
																			type: "option",
																			value: "Banking",
																		},
																		{
																			title: "Business",
																			type: "option",
																			value: "Business",
																		},
																		{
																			title: "Other",
																			type: "option",
																			value: "Other",
																		},
																	]}
																	style={{
																		"--framer-input-background":
																			"var(--token-cd35caec-4f2a-4f7e-8c70-9992720e55b3, rgba(51, 51, 51, 0.2))",
																		"--framer-input-border-bottom-width": "1px",
																		"--framer-input-border-color":
																			"var(--token-30ee69d1-cae6-4a5c-9af2-db5c94a12e77, rgba(255, 255, 255, 0.05))",
																		"--framer-input-border-left-width": "1px",
																		"--framer-input-border-radius-bottom-left":
																			"5px",
																		"--framer-input-border-radius-bottom-right":
																			"5px",
																		"--framer-input-border-radius-top-left":
																			"5px",
																		"--framer-input-border-radius-top-right":
																			"5px",
																		"--framer-input-border-right-width": "1px",
																		"--framer-input-border-style": "solid",
																		"--framer-input-border-top-width": "1px",
																		"--framer-input-font-color":
																			"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
																		"--framer-input-icon-color":
																			"rgb(153, 153, 153)",
																		"--framer-input-invalid-text-color":
																			"var(--token-3f9a2c63-f1d1-4706-bf6c-31956c981af9, rgb(153, 153, 153))",
																	}}
																/>
															</motion.label>
														</motion.div>
														<motion.label
															className={"framer-1o70lpc"}
															data-framer-name={"Message"}
															layoutDependency={layoutDependency}
															layoutId={"ayy2mrOOQ"}
														>
															<RichText
																__fromCanvasComponent={true}
																className={"framer-mnrs2"}
																data-framer-name={"Text"}
																fonts={["Inter"]}
																layoutDependency={layoutDependency}
																layoutId={"pjAwWLwqv"}
																verticalAlignment={"top"}
																withExternalLayout={true}
															>
																<React.Fragment>
																	<motion.p
																		className={"framer-styles-preset-1gjbdzu"}
																		data-styles-preset={"JQSP3EtUD"}
																	>
																		{"Message*"}
																	</motion.p>
																</React.Fragment>
															</RichText>
															<FormPlainTextInput
																className={"framer-162wzdz"}
																inputName={"Name"}
																layoutDependency={layoutDependency}
																layoutId={"MjPWpBzDC"}
																placeholder={"Type your message..."}
																required={true}
																style={{
																	"--framer-input-background":
																		"var(--token-cd35caec-4f2a-4f7e-8c70-9992720e55b3, rgba(51, 51, 51, 0.2))",
																	"--framer-input-border-bottom-width": "1px",
																	"--framer-input-border-color":
																		"var(--token-30ee69d1-cae6-4a5c-9af2-db5c94a12e77, rgba(255, 255, 255, 0.05))",
																	"--framer-input-border-left-width": "1px",
																	"--framer-input-border-radius-bottom-left":
																		"5px",
																	"--framer-input-border-radius-bottom-right":
																		"5px",
																	"--framer-input-border-radius-top-left":
																		"5px",
																	"--framer-input-border-radius-top-right":
																		"5px",
																	"--framer-input-border-right-width": "1px",
																	"--framer-input-border-style": "solid",
																	"--framer-input-border-top-width": "1px",
																	"--framer-input-font-color":
																		"var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))",
																	"--framer-input-icon-color":
																		"rgb(153, 153, 153)",
																	"--framer-input-placeholder-color":
																		"var(--token-3f9a2c63-f1d1-4706-bf6c-31956c981af9, rgb(153, 153, 153))",
																}}
																type={"textarea"}
															/>
														</motion.label>
														<ComponentViewportProvider
															height={50}
															width={`calc(max(max(min(${componentViewport?.width || "100vw"} - 160px, 1200px) - 20px, 1px) - 2px, 1px) - 80px)`}
															{...addPropertyOverrides(
																{
																	g2hNi2hXF: {
																		width: `calc(max(max(min(${componentViewport?.width || "100vw"} - 60px, 1200px) - 20px, 1px) - 2px, 1px) - 60px)`,
																	},
																	XP32tdAQ6: {
																		width: `calc(max(max(min(${componentViewport?.width || "100vw"} - 100px, 1200px) - 20px, 1px) - 2px, 1px) - 80px)`,
																	},
																},
																baseVariant,
																gestureVariant,
															)}
														>
															<SmartComponentScopedContainer
																className={"framer-lh4zze-container"}
																layoutDependency={layoutDependency}
																layoutId={"SQZlcAmZd-container"}
																nodeId={"SQZlcAmZd"}
																rendersWithMotion={true}
																scopeId={"VcycPnV9B"}
															>
																{_jsx(stdin_default3, {
																	height: "100%",
																	id: "SQZlcAmZd",
																	layoutId: "SQZlcAmZd",
																	style: {
																		width: "100%",
																	},
																	type: "submit",
																	variant: formVariants(
																		formState,
																		{
																			pending: "pVumzGZCv",
																			success: "QHCIz2XOl",
																		},
																		"OnYleudVI",
																	),
																	width: "100%",
																})}
															</SmartComponentScopedContainer>
														</ComponentViewportProvider>
													</_Fragment>
												)}
											</FormContainer>
										</motion.div>
									</motion.div>
								</motion.div>
							</MotionDivWithFXWithOptimizedAppearEffect>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-DHik3.framer-17o5537, .framer-DHik3 .framer-17o5537 { display: block; }",
	".framer-DHik3.framer-1bjp701 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 70px; height: min-content; justify-content: flex-start; max-width: 1440px; overflow: hidden; padding: 0px 0px 120px 0px; position: relative; width: 1200px; }",
	".framer-DHik3 .framer-1tkruiv { flex: none; height: 91px; overflow: hidden; position: relative; width: 100%; }",
	".framer-DHik3 .framer-acqazr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 70px; height: min-content; justify-content: center; overflow: visible; padding: 0px 80px 0px 80px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-117r0ss { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 0; }",
	".framer-DHik3 .framer-r52apt { flex: none; height: 101%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 101% / 2); width: 100%; z-index: 1; }",
	".framer-DHik3 .framer-1cmchmt { bottom: 0px; flex: none; height: 224px; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; width: 100%; z-index: 1; }",
	".framer-DHik3 .framer-14aeo17 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 38px; height: min-content; justify-content: center; max-width: 980px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-DHik3 .framer-19sish5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-1676zb2 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 34px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-v0gqac-container, .framer-DHik3 .framer-14ttus3-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-DHik3 .framer-cw5ibw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-ngp4ar, .framer-DHik3 .framer-13ympta { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-DHik3 .framer-1mouatl { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 500px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-15exkix { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-DHik3 .framer-rkm0zu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; max-width: 600px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-4t83n5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 1; }",
	".framer-DHik3 .framer-1lqmbnu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 10px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-a4nmtn { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 1px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-DHik3 .framer-1uvffyy { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-DHik3 .framer-65elbn { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 40px 40px 30px 40px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-hh95lm, .framer-DHik3 .framer-5ux4en { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-DHik3 .framer-1yox3eu, .framer-DHik3 .framer-k3o1go, .framer-DHik3 .framer-1fggqtg, .framer-DHik3 .framer-olgzgc { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 1px; }",
	".framer-DHik3 .framer-n7zn46, .framer-DHik3 .framer-1woa6ie, .framer-DHik3 .framer-cle1l4, .framer-DHik3 .framer-qj37es, .framer-DHik3 .framer-1nroqcl, .framer-DHik3 .framer-mnrs2 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	'.framer-DHik3 .framer-1ivn5ez, .framer-DHik3 .framer-p3yxdp, .framer-DHik3 .framer-1qk866z, .framer-DHik3 .framer-1tjjjiy, .framer-DHik3 .framer-138kdiq { --framer-input-focused-border-color: var(--token-f951c3a8-aa43-4825-aa75-915aa92c20d1, #4f1ad6); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "DM Sans"; --framer-input-font-letter-spacing: -0.5px; --framer-input-font-line-height: 20px; --framer-input-font-size: 16px; --framer-input-font-weight: 500; --framer-input-padding: 18px; --framer-input-wrapper-height: auto; flex: none; height: auto; position: relative; width: 100%; }',
	".framer-DHik3 .framer-1e8vvoz, .framer-DHik3 .framer-1o70lpc { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	'.framer-DHik3 .framer-162wzdz { --framer-input-focused-border-color: var(--token-f951c3a8-aa43-4825-aa75-915aa92c20d1, #4f1ad6); --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "DM Sans"; --framer-input-font-letter-spacing: -0.5px; --framer-input-font-line-height: 20px; --framer-input-font-size: 16px; --framer-input-font-weight: 500; --framer-input-padding: 18px; --framer-input-wrapper-height: auto; flex: none; height: auto; min-height: 100px; position: relative; width: 100%; }',
	".framer-DHik3 .framer-lh4zze-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-DHik3.framer-v-75r16k.framer-1bjp701 { padding: 0px 0px 100px 0px; width: 810px; }",
	".framer-DHik3.framer-v-75r16k .framer-acqazr { padding: 0px 50px 0px 50px; }",
	".framer-DHik3.framer-v-1pgqt8g.framer-1bjp701 { padding: 0px 0px 80px 0px; width: 390px; }",
	".framer-DHik3.framer-v-1pgqt8g .framer-acqazr { align-content: flex-start; align-items: flex-start; padding: 0px 30px 0px 30px; }",
	".framer-DHik3.framer-v-1pgqt8g .framer-14aeo17 { align-content: flex-start; align-items: flex-start; max-width: 460px; }",
	".framer-DHik3.framer-v-1pgqt8g .framer-19sish5, .framer-DHik3.framer-v-1pgqt8g .framer-1676zb2 { align-content: flex-start; align-items: flex-start; }",
	".framer-DHik3.framer-v-1pgqt8g .framer-rkm0zu { justify-content: flex-start; }",
	".framer-DHik3.framer-v-1pgqt8g .framer-65elbn { padding: 30px; }",
	".framer-DHik3.framer-v-1pgqt8g .framer-hh95lm, .framer-DHik3.framer-v-1pgqt8g .framer-5ux4en { flex-direction: column; }",
	".framer-DHik3.framer-v-1pgqt8g .framer-1yox3eu, .framer-DHik3.framer-v-1pgqt8g .framer-k3o1go, .framer-DHik3.framer-v-1pgqt8g .framer-1fggqtg, .framer-DHik3.framer-v-1pgqt8g .framer-olgzgc { flex: none; width: 100%; }",
	...css2,
	...css,
	...css3,
	'.framer-DHik3[data-border="true"]::after, .framer-DHik3 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerVcycPnV9B = withCSS(Component, css4, "framer-DHik3");
var stdin_default4 = FramerVcycPnV9B;
FramerVcycPnV9B.displayName = "Hero-Contact";
FramerVcycPnV9B.defaultProps = {
	height: 1461,
	width: 1200,
};
addPropertyControls(FramerVcycPnV9B, {
	variant: {
		options: ["O_PbKerS_", "XP32tdAQ6", "g2hNi2hXF"],
		optionTitles: ["L", "M", "S"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerVcycPnV9B,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "DM Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "DM Sans",
					url: "https://fonts.gstatic.com/s/dmsans/v17/rP2tp2ywxg089UriI5-g4vlH9VoD8CmcqZG40F9JadbnoEwAkJxhS2f3ZGMZpg.woff2",
					weight: "500",
				},
			],
		},
		...TagPrimaryTagFonts,
		...ButtonPrimaryButtonFonts,
		...ButtonContactButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero-contact
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "g2hNi2hXF",
	md: "XP32tdAQ6",
	xl: "O_PbKerS_",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroContactFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var hero_contact_default = ComponentWithRoot;
export { hero_contact_default as default };
