// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M' | 'S' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KOW5QF4M.js";
import { className, css, fonts } from "./chunks/chunk-6RBWXANE.js";
import { stdin_default } from "./chunks/chunk-JQY6WALF.js";
import "./chunks/chunk-IXDMRUES.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-XIXCBJDO.js";

// virtual:hero-about-me
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/vYOlwPfZtkSddYgEvkCM/mfEQyqeHFGDcRc5CELjF/cSJr7wozc.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var TagPrimaryTagFonts = getFonts(stdin_default);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var cycleOrder = ["ZrF8mkuGo", "rz3KBhna6", "pbpwIx_mm"];
var serializationHash = "framer-jKX0o";
var variantClassNames = {
	pbpwIx_mm: "framer-v-1jm77oa",
	rz3KBhna6: "framer-v-1dskkb7",
	ZrF8mkuGo: "framer-v-1rsusfa",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	damping: 60,
	delay: 0.5,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var transition4 = {
	damping: 60,
	delay: 0.7,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var animation4 = {
	filter: "blur(10px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition5 = {
	damping: 50,
	delay: 0.05,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var textEffect = {
	effect: animation4,
	repeat: false,
	startDelay: 0.9,
	tokenization: "word",
	transition: transition5,
	trigger: "onMount",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	L: "ZrF8mkuGo",
	M: "rz3KBhna6",
	S: "pbpwIx_mm",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ZrF8mkuGo",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ZrF8mkuGo",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1rsusfa",
							className3,
							classNames,
						)}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"ZrF8mkuGo"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								pbpwIx_mm: {
									"data-framer-name": "S",
								},
								rz3KBhna6: {
									"data-framer-name": "M",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-rphf9s"}
							data-framer-name={"Spacer"}
							layoutDependency={layoutDependency}
							layoutId={"q70JVbCi5"}
						/>
						<motion.div
							className={"framer-1kga82q"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"h4uvbIUyR"}
							style={{
								background:
									"radial-gradient(60% 88% at 50% 64.2%, var(--token-f951c3a8-aa43-4825-aa75-915aa92c20d1, rgb(79, 26, 214)) 0%, rgb(114, 59, 255) 39.99155405405405%, var(--token-123b0380-d5c1-475a-b484-6e62cac5babe, rgb(25, 13, 46)) 84.93278434684684%, rgb(0, 0, 0) 100%)",
							}}
						>
							<motion.div
								className={"framer-163cnt8"}
								data-framer-name={"Gradient Bottom"}
								layoutDependency={layoutDependency}
								layoutId={"KBtLi0DXd"}
								style={{
									background:
										"linear-gradient(180deg, rgba(255, 255, 255, 0) 0%, rgb(0, 0, 0) 100%)",
								}}
							/>
							<motion.div
								className={"framer-zz34dl"}
								data-framer-name={"Particles "}
								layoutDependency={layoutDependency}
								layoutId={"utb_j5uAA"}
							>
								<motion.div
									className={"framer-1jt0gku"}
									data-framer-name={"Vignette"}
									layoutDependency={layoutDependency}
									layoutId={"lq1uGtrCR"}
									style={{
										background:
											"radial-gradient(54% 50% at 50% 57.199999999999996%, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.67) 64.51471002252252%, rgb(0, 0, 0) 100%)",
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-1ghkv7v"}
								data-framer-name={"Top"}
								layoutDependency={layoutDependency}
								layoutId={"vor5h8r2z"}
							>
								<motion.div
									className={"framer-rpcq1d"}
									data-framer-name={"Text/Tag"}
									layoutDependency={layoutDependency}
									layoutId={"F522IOFXy"}
								>
									<motion.div
										className={"framer-u3q236"}
										data-framer-name={"Tag & Title"}
										layoutDependency={layoutDependency}
										layoutId={"ma28_kkwe"}
									>
										<ComponentViewportProvider
											height={40}
											y={
												(componentViewport?.y || 0) +
												0 +
												161 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0
											}
										>
											<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation}
												className={"framer-1w47gc4-container"}
												data-framer-appear-id={"1w47gc4"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"lh6JObpXK-container"}
												nodeId={"lh6JObpXK"}
												optimized={true}
												rendersWithMotion={true}
												scopeId={"cSJr7wozc"}
											>
												{_jsx(stdin_default, {
													aZ7GvMqIl: "Acorn",
													height: "100%",
													id: "lh6JObpXK",
													KS7KLFqN8: "The Journey of Reeva",
													layoutId: "lh6JObpXK",
													rQKAY6456: "2025",
													variant: "AksRoqhcS",
													width: "100%",
													xAPRy8bad: 0,
												})}
											</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
										</ComponentViewportProvider>
										<motion.div
											className={"framer-7ta2jd"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"EH_xWq3PW"}
										>
											<RichTextWithFXWithOptimizedAppearEffect
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation2}
												className={"framer-1epm5vf"}
												data-framer-appear-id={"1epm5vf"}
												data-framer-name={"Text 1"}
												fonts={["Inter"]}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"tKL7k5XTh"}
												optimized={true}
												style={{
													"--extracted-gdpscs": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														pbpwIx_mm: {
															children: (
																<React.Fragment>
																	<motion.h1
																		className={"framer-styles-preset-1idioqq"}
																		data-styles-preset={"ABKs9wxVy"}
																		style={{
																			"--framer-text-alignment": "left",
																			"--framer-text-color":
																				"var(--extracted-gdpscs, rgb(255, 255, 255))",
																		}}
																	>
																		<motion.span
																			data-text-fill={"true"}
																			style={{
																				backgroundImage:
																					"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
																			}}
																		>
																			{"Building Simple Tools "}
																		</motion.span>
																	</motion.h1>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.h1
														className={"framer-styles-preset-1idioqq"}
														data-styles-preset={"ABKs9wxVy"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
															}}
														>
															{"Building Simple Tools "}
														</motion.span>
													</motion.h1>
												</React.Fragment>
											</RichTextWithFXWithOptimizedAppearEffect>
											<RichTextWithFXWithOptimizedAppearEffect
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation3}
												className={"framer-b6y8g6"}
												data-framer-appear-id={"b6y8g6"}
												data-framer-name={"Text 2"}
												fonts={["Inter"]}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"OrVCLNzrX"}
												optimized={true}
												style={{
													"--extracted-gdpscs": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														pbpwIx_mm: {
															children: (
																<React.Fragment>
																	<motion.h1
																		className={"framer-styles-preset-1idioqq"}
																		data-styles-preset={"ABKs9wxVy"}
																		style={{
																			"--framer-text-alignment": "left",
																			"--framer-text-color":
																				"var(--extracted-gdpscs, rgb(255, 255, 255))",
																		}}
																	>
																		<motion.span
																			data-text-fill={"true"}
																			style={{
																				backgroundImage:
																					"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
																			}}
																		>
																			{"for Real Frustrations."}
																		</motion.span>
																	</motion.h1>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.h1
														className={"framer-styles-preset-1idioqq"}
														data-styles-preset={"ABKs9wxVy"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
															}}
														>
															{"for Real Frustrations."}
														</motion.span>
													</motion.h1>
												</React.Fragment>
											</RichTextWithFXWithOptimizedAppearEffect>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-yivnwz"}
										data-framer-name={"Body"}
										layoutDependency={layoutDependency}
										layoutId={"IgbXOtnzP"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1vrh7ia"}
											data-framer-name={"Text"}
											effect={textEffect}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"KDbCDgHhT"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											variants={{
												pbpwIx_mm: {
													"--extracted-r6o4lv":
														"var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6))",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													pbpwIx_mm: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-x0s9r5"}
																	data-styles-preset={"QhK6qqT5U"}
																	style={{
																		"--framer-text-alignment": "left",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6)))",
																	}}
																>
																	{
																		"Landin is your go-to agency for creative thinking and marketing ideas. We specialize in digital business solutions."
																	}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-x0s9r5"}
													data-styles-preset={"QhK6qqT5U"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{
														"Reeva was born from one small annoyance \u2014 never finding the Reels you save. Now, it\u2019s growing into a product that helps millions rediscover what they love, and creators understand what people actually save."
													}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-jKX0o.framer-146pdnk, .framer-jKX0o .framer-146pdnk { display: block; }",
	".framer-jKX0o.framer-1rsusfa { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 70px; height: min-content; justify-content: flex-start; max-width: 1440px; overflow: visible; padding: 0px; position: relative; width: 1200px; }",
	".framer-jKX0o .framer-rphf9s { flex: none; height: 91px; overflow: hidden; position: relative; width: 100%; }",
	".framer-jKX0o .framer-1kga82q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px 80px 0px 80px; position: relative; width: 100%; }",
	".framer-jKX0o .framer-163cnt8 { bottom: 0px; flex: none; height: 224px; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; width: 100%; z-index: 1; }",
	".framer-jKX0o .framer-zz34dl { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; padding: 0px; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; z-index: 0; }",
	".framer-jKX0o .framer-1jt0gku { flex: none; height: 101%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 101% / 2); width: 100%; z-index: 1; }",
	".framer-jKX0o .framer-1ghkv7v { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 38px; height: min-content; justify-content: center; max-width: 980px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-jKX0o .framer-rpcq1d { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-jKX0o .framer-u3q236 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 34px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-jKX0o .framer-1w47gc4-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-jKX0o .framer-7ta2jd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-jKX0o .framer-1epm5vf, .framer-jKX0o .framer-b6y8g6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-jKX0o .framer-yivnwz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 500px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-jKX0o .framer-1vrh7ia { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-jKX0o.framer-v-1dskkb7.framer-1rsusfa { width: 810px; }",
	".framer-jKX0o.framer-v-1dskkb7 .framer-1kga82q { padding: 0px 50px 0px 50px; }",
	".framer-jKX0o.framer-v-1jm77oa.framer-1rsusfa { width: 390px; }",
	".framer-jKX0o.framer-v-1jm77oa .framer-1kga82q { align-content: flex-start; align-items: flex-start; padding: 0px 30px 0px 30px; }",
	".framer-jKX0o.framer-v-1jm77oa .framer-1ghkv7v { align-content: flex-start; align-items: flex-start; max-width: 460px; }",
	".framer-jKX0o.framer-v-1jm77oa .framer-rpcq1d, .framer-jKX0o.framer-v-1jm77oa .framer-u3q236, .framer-jKX0o.framer-v-1jm77oa .framer-7ta2jd { align-content: flex-start; align-items: flex-start; }",
	...css2,
	...css,
];
var FramercSJr7wozc = withCSS(Component, css3, "framer-jKX0o");
var stdin_default2 = FramercSJr7wozc;
FramercSJr7wozc.displayName = "Hero-AboutMe";
FramercSJr7wozc.defaultProps = {
	height: 547,
	width: 1200,
};
addPropertyControls(FramercSJr7wozc, {
	variant: {
		options: ["ZrF8mkuGo", "rz3KBhna6", "pbpwIx_mm"],
		optionTitles: ["L", "M", "S"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramercSJr7wozc,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagPrimaryTagFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero-about-me
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "pbpwIx_mm",
	md: "rz3KBhna6",
	xl: "ZrF8mkuGo",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroAboutMeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var hero_about_me_default = ComponentWithRoot;
export { hero_about_me_default as default };
