// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M' | 'S' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-KOW5QF4M.js";
import { className, css, fonts } from "./chunks/chunk-6RBWXANE.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-JQY6WALF.js";
import "./chunks/chunk-IXDMRUES.js";
import "./chunks/chunk-BVM6H744.js";
import { stdin_default } from "./chunks/chunk-6S67OR3F.js";
import "./chunks/chunk-ZGMLUSG3.js";
import { routes } from "./chunks/chunk-XIXCBJDO.js";

// virtual:hero-404
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7OAHbQQXqpsKjvH1XiKk/1pFCepRL9zKsPsu5IKhR/wXsyytOmp.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	ResolveLinks,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var TagPrimaryTagFonts = getFonts(stdin_default2);
var SmartComponentScopedContainerWithFXWithOptimizedAppearEffect =
	withOptimizedAppearEffect(withFX(SmartComponentScopedContainer));
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var ButtonPrimaryButtonFonts = getFonts(stdin_default);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var cycleOrder = ["f9f1Rnhvz", "sWAszhPdZ", "aQRkDdUN6"];
var serializationHash = "framer-NXNPB";
var variantClassNames = {
	aQRkDdUN6: "framer-v-hn1rof",
	f9f1Rnhvz: "framer-v-1072udn",
	sWAszhPdZ: "framer-v-9iems4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	damping: 60,
	delay: 0.2,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	damping: 60,
	delay: 0.5,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation2 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var transition4 = {
	damping: 60,
	delay: 0.7,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation3 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition4,
	x: 0,
	y: 0,
};
var animation4 = {
	filter: "blur(10px)",
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition5 = {
	damping: 50,
	delay: 0.05,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var textEffect = {
	effect: animation4,
	repeat: false,
	startDelay: 0.9,
	tokenization: "word",
	transition: transition5,
	trigger: "onMount",
	type: "appear",
};
var transition6 = {
	damping: 60,
	delay: 1.1,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var animation5 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition6,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	L: "f9f1Rnhvz",
	M: "sWAszhPdZ",
	S: "aQRkDdUN6",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "f9f1Rnhvz",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "f9f1Rnhvz",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1072udn",
							className3,
							classNames,
						)}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"f9f1Rnhvz"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								aQRkDdUN6: {
									"data-framer-name": "S",
								},
								sWAszhPdZ: {
									"data-framer-name": "M",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1y34kq8"}
							data-framer-name={"Spacer"}
							layoutDependency={layoutDependency}
							layoutId={"coSk8IiPZ"}
							style={{ height: "0px" }}
						/>
						<motion.div
							className={"framer-1adchwi"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"tLUi45ttp"}
						>
							<motion.div
								className={"framer-hudot8"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"Eqfi7thmb"}
							>
								<motion.div
									className={"framer-wsbb7q"}
									data-framer-name={"Text/Tag"}
									layoutDependency={layoutDependency}
									layoutId={"DFZx4luEU"}
								>
									<motion.div
										className={"framer-y3wvwd"}
										data-framer-name={"Tag & Title"}
										layoutDependency={layoutDependency}
										layoutId={"KBGWvOUay"}
									>
										<ComponentViewportProvider
											height={40}
											y={
												(componentViewport?.y || 0) +
												0 +
												200 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0 +
												0
											}
											{...addPropertyOverrides(
												{
													aQRkDdUN6: {
														y:
															(componentViewport?.y || 0) +
															0 +
															160 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0,
													},
													sWAszhPdZ: {
														y:
															(componentViewport?.y || 0) +
															0 +
															180 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainerWithFXWithOptimizedAppearEffect
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation}
												className={"framer-2vpcau-container"}
												data-framer-appear-id={"2vpcau"}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"jGMUiv_90-container"}
												nodeId={"jGMUiv_90"}
												optimized={true}
												rendersWithMotion={true}
												scopeId={"wXsyytOmp"}
											>
												{_jsx(stdin_default2, {
													aZ7GvMqIl: "Acorn",
													height: "100%",
													id: "jGMUiv_90",
													KS7KLFqN8: "Page Not Found",
													layoutId: "jGMUiv_90",
													rQKAY6456: "OOPS",
													variant: "AksRoqhcS",
													width: "100%",
													xAPRy8bad: 0,
												})}
											</SmartComponentScopedContainerWithFXWithOptimizedAppearEffect>
										</ComponentViewportProvider>
										<motion.div
											className={"framer-1yaa1pv"}
											data-framer-name={"Title"}
											layoutDependency={layoutDependency}
											layoutId={"sVe3a6S_7"}
										>
											<RichTextWithFXWithOptimizedAppearEffect
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation2}
												className={"framer-ezru78"}
												data-framer-appear-id={"ezru78"}
												data-framer-name={"Text 1"}
												fonts={["Inter"]}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"n0HqWN_Ks"}
												optimized={true}
												style={{
													"--extracted-gdpscs": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
												{...addPropertyOverrides(
													{
														aQRkDdUN6: {
															children: (
																<React.Fragment>
																	<motion.h1
																		className={"framer-styles-preset-1idioqq"}
																		data-styles-preset={"ABKs9wxVy"}
																		style={{
																			"--framer-text-alignment": "center",
																			"--framer-text-color":
																				"var(--extracted-gdpscs, rgb(255, 255, 255))",
																		}}
																	>
																		<motion.span
																			data-text-fill={"true"}
																			style={{
																				backgroundImage:
																					"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
																			}}
																		>
																			{"404 - Oops Page "}
																		</motion.span>
																	</motion.h1>
																</React.Fragment>
															),
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<React.Fragment>
													<motion.h1
														className={"framer-styles-preset-1idioqq"}
														data-styles-preset={"ABKs9wxVy"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
															}}
														>
															{"404 - Oops Page"}
														</motion.span>
													</motion.h1>
												</React.Fragment>
											</RichTextWithFXWithOptimizedAppearEffect>
											<RichTextWithFXWithOptimizedAppearEffect
												__fromCanvasComponent={true}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												animate={animation3}
												className={"framer-1t1ig00"}
												data-framer-appear-id={"1t1ig00"}
												data-framer-name={"Text 2"}
												fonts={["Inter"]}
												initial={animation1}
												layoutDependency={layoutDependency}
												layoutId={"RObpqpcFZ"}
												optimized={true}
												style={{
													"--extracted-gdpscs": "rgb(255, 255, 255)",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h1
														className={"framer-styles-preset-1idioqq"}
														data-styles-preset={"ABKs9wxVy"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-gdpscs, rgb(255, 255, 255))",
														}}
													>
														<motion.span
															data-text-fill={"true"}
															style={{
																backgroundImage:
																	"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
															}}
														>
															{"Not Found in Data."}
														</motion.span>
													</motion.h1>
												</React.Fragment>
											</RichTextWithFXWithOptimizedAppearEffect>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-1l51y1"}
										data-framer-name={"Body"}
										layoutDependency={layoutDependency}
										layoutId={"ZGBDw7mVQ"}
									>
										<RichTextWithFXWithOptimizedAppearEffect
											__fromCanvasComponent={true}
											__perspectiveFX={false}
											__smartComponentFX={true}
											__targetOpacity={1}
											animate={animation2}
											className={"framer-r4w771"}
											data-framer-appear-id={"r4w771"}
											data-framer-name={"Text"}
											fonts={["Inter"]}
											initial={animation1}
											layoutDependency={layoutDependency}
											layoutId={"s0yhe0MIQ"}
											optimized={true}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													aQRkDdUN6: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-x0s9r5"}
																	data-styles-preset={"QhK6qqT5U"}
																	style={{
																		"--framer-text-alignment": "center",
																	}}
																>
																	{
																		"Oops! The web page you\u2019re looking for doesn\u2019t exist. Please click the below button to get back to the home."
																	}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-x0s9r5"}
													data-styles-preset={"QhK6qqT5U"}
													style={{
														"--framer-text-alignment": "center",
													}}
												>
													{
														"Oops! The web page you\u2019re looking for doesn\u2019t"
													}
													<motion.br />
													{
														" exist. Please click the below button to get back to the home."
													}
												</motion.p>
											</React.Fragment>
										</RichTextWithFXWithOptimizedAppearEffect>
									</motion.div>
								</motion.div>
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation5}
									className={"framer-owvvk9"}
									data-framer-appear-id={"owvvk9"}
									data-framer-name={"Button"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"B_pSAWUsQ"}
									optimized={true}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "augiA20Il",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={46}
												y={
													(componentViewport?.y || 0) +
													0 +
													200 +
													0 +
													0 +
													0 +
													448 +
													0
												}
												{...addPropertyOverrides(
													{
														aQRkDdUN6: {
															y:
																(componentViewport?.y || 0) +
																0 +
																160 +
																0 +
																0 +
																0 +
																448 +
																0,
														},
														sWAszhPdZ: {
															y:
																(componentViewport?.y || 0) +
																0 +
																180 +
																0 +
																0 +
																0 +
																448 +
																0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-1hhrh94-container"}
													layoutDependency={layoutDependency}
													layoutId={"Yfwx6wf3C-container"}
													nodeId={"Yfwx6wf3C"}
													rendersWithMotion={true}
													scopeId={"wXsyytOmp"}
												>
													{_jsx(stdin_default, {
														AL_NU982V: false,
														dlVBgpKLv: "Back To Homepage",
														GT109pdEG: resolvedLinks[0],
														height: "100%",
														id: "Yfwx6wf3C",
														layoutId: "Yfwx6wf3C",
														SD1BGlGhK: false,
														variant: "vf6JWDf13",
														width: "100%",
														YVFZiszrG: {
															borderColor:
																"var(--token-a58752c8-168c-47db-857e-906f22f33790, rgba(255, 255, 255, 0.15))",
															borderStyle: "solid",
															borderWidth: 3,
														},
														...addPropertyOverrides(
															{
																aQRkDdUN6: {
																	GT109pdEG: resolvedLinks[2],
																},
																sWAszhPdZ: {
																	GT109pdEG: resolvedLinks[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
								</MotionDivWithFXWithOptimizedAppearEffect>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-NXNPB.framer-1m8krah, .framer-NXNPB .framer-1m8krah { display: block; }",
	".framer-NXNPB.framer-1072udn { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: flex-start; max-width: 1480px; overflow: visible; padding: 0px 80px 160px 80px; position: relative; width: 1200px; }",
	".framer-NXNPB .framer-1y34kq8 { flex: none; height: 80px; overflow: hidden; position: relative; width: 100%; }",
	".framer-NXNPB .framer-1adchwi { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 70px; height: min-content; justify-content: center; overflow: visible; padding: 0px 120px 0px 120px; position: relative; width: 100%; }",
	".framer-NXNPB .framer-hudot8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 38px; height: min-content; justify-content: center; max-width: 980px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-NXNPB .framer-wsbb7q { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-NXNPB .framer-y3wvwd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 34px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-NXNPB .framer-2vpcau-container, .framer-NXNPB .framer-1hhrh94-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-NXNPB .framer-1yaa1pv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-NXNPB .framer-ezru78, .framer-NXNPB .framer-1t1ig00 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-NXNPB .framer-1l51y1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 500px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-NXNPB .framer-r4w771 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-NXNPB .framer-owvvk9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; max-width: 600px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-NXNPB.framer-v-9iems4.framer-1072udn { gap: 100px; padding: 0px 80px 120px 80px; width: 810px; }",
	".framer-NXNPB.framer-v-9iems4 .framer-1adchwi { padding: 0px 50px 0px 50px; }",
	".framer-NXNPB.framer-v-hn1rof.framer-1072udn { gap: 80px; padding: 0px 30px 120px 30px; width: 200px; }",
	".framer-NXNPB.framer-v-hn1rof .framer-1adchwi { padding: 0px 30px 0px 30px; }",
	".framer-NXNPB.framer-v-hn1rof .framer-hudot8 { max-width: 460px; }",
	...css2,
	...css,
];
var FramerwXsyytOmp = withCSS(Component, css3, "framer-NXNPB");
var stdin_default3 = FramerwXsyytOmp;
FramerwXsyytOmp.displayName = "Hero-404";
FramerwXsyytOmp.defaultProps = {
	height: 778,
	width: 1200,
};
addPropertyControls(FramerwXsyytOmp, {
	variant: {
		options: ["f9f1Rnhvz", "sWAszhPdZ", "aQRkDdUN6"],
		optionTitles: ["L", "M", "S"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerwXsyytOmp,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagPrimaryTagFonts,
		...ButtonPrimaryButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:hero-404
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "aQRkDdUN6",
	md: "sWAszhPdZ",
	xl: "f9f1Rnhvz",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Hero404FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var hero_404_default = ComponentWithRoot;
export { hero_404_default as default };
