// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'L' | 'M' | 'S' // Variant
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-SWVNVNLK.js";
import {
	className as className5,
	className2 as className6,
	className3 as className7,
	css as css5,
	css2 as css6,
	css3 as css7,
	fonts as fonts5,
	fonts2 as fonts6,
	fonts3 as fonts7,
} from "./chunks/chunk-A6GGRY7P.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-KOW5QF4M.js";
import { className, css, fonts } from "./chunks/chunk-X3WHOS63.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-IUVHVVOX.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-6RBWXANE.js";
import { stdin_default } from "./chunks/chunk-JQY6WALF.js";
import "./chunks/chunk-IXDMRUES.js";
import "./chunks/chunk-BVM6H744.js";
import { routes } from "./chunks/chunk-XIXCBJDO.js";

// virtual:main-terms-conditions
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/tb0fBCUX7tbd1bEGLA2D/KBOQSur2Fdl3FcTxjjAC/LUMOn5XcA.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	PathVariablesContext,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleCode,
	useLocaleInfo,
	useQueryData,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var TagPrimaryTagFonts = getFonts(stdin_default);
var cycleOrder = ["zM2zLXAnh", "qQZf7tA7c", "xA_6Q6tyB"];
var serializationHash = "framer-PSZhG";
var variantClassNames = {
	qQZf7tA7c: "framer-v-z80r7a",
	xA_6Q6tyB: "framer-v-1rumc1j",
	zM2zLXAnh: "framer-v-wka6op",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var sharedDateFormatter = (value, formatOptions, locale) => {
	if (typeof value !== "string") return "";
	const date = new Date(value);
	if (isNaN(date.getTime())) return "";
	const fallbackLocale = "en-US";
	try {
		return date.toLocaleString(locale || fallbackLocale, formatOptions);
	} catch {
		return date.toLocaleString(fallbackLocale, formatOptions);
	}
};
var dateOptions = {
	dateStyle: "medium",
	timeStyle: "short",
	timeZone: "UTC",
};
var toDateString = (value, activeLocale) => {
	return sharedDateFormatter(value, dateOptions, activeLocale);
};
var prefix = (value, prefix2) => {
	if (typeof value === "string" && typeof prefix2 === "string") {
		return prefix2 + value;
	} else if (typeof value === "string") {
		return value;
	} else if (typeof prefix2 === "string") {
		return prefix2;
	}
	return "";
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData(query2);
	return children(data);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	L: "zM2zLXAnh",
	M: "qQZf7tA7c",
	S: "xA_6Q6tyB",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zM2zLXAnh",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className8,
		layoutId,
		variant,
		yn3XiFF9SzKxT5CQtu,
		WxefFDjNTzKxT5CQtu,
		NHqcQ4k6ozKxT5CQtu,
		uBrouiWbvzKxT5CQtu,
		zSxRelg24zKxT5CQtu,
		jQLZtPWi0zKxT5CQtu,
		idzKxT5CQtu,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zM2zLXAnh",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className4,
		className2,
		className,
		className3,
		className7,
		className5,
		className6,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const activeLocaleCode = useLocaleCode();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.section
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-wka6op",
							className8,
							classNames,
						)}
						data-framer-name={"L"}
						layoutDependency={layoutDependency}
						layoutId={"zM2zLXAnh"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								qQZf7tA7c: {
									"data-framer-name": "M",
								},
								xA_6Q6tyB: {
									"data-framer-name": "S",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-bnv7tl"}
							data-framer-name={"Spacer"}
							layoutDependency={layoutDependency}
							layoutId={"roSAI3b_u"}
						/>
						<motion.div
							className={"framer-e7up6d"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"YAzu7mnbT"}
						>
							<motion.div
								className={"framer-1jlcn1n"}
								layoutDependency={layoutDependency}
								layoutId={"zKxT5CQtu"}
							>
								<ChildrenCanSuspend>
									<QueryData
										query={{
											from: {
												alias: "zKxT5CQtu",
												data: stdin_default2,
												type: "Collection",
											},
											limit: {
												type: "LiteralValue",
												value: 1,
											},
											select: [
												{
													collection: "zKxT5CQtu",
													name: "yn3XiFF9S",
													type: "Identifier",
												},
												{
													collection: "zKxT5CQtu",
													name: "WxefFDjNT",
													type: "Identifier",
												},
												{
													collection: "zKxT5CQtu",
													name: "NHqcQ4k6o",
													type: "Identifier",
												},
												{
													collection: "zKxT5CQtu",
													name: "uBrouiWbv",
													type: "Identifier",
												},
												{
													collection: "zKxT5CQtu",
													name: "zSxRelg24",
													type: "Identifier",
												},
												{
													collection: "zKxT5CQtu",
													name: "jQLZtPWi0",
													type: "Identifier",
												},
												{
													collection: "zKxT5CQtu",
													name: "id",
													type: "Identifier",
												},
											],
										}}
									>
										{(collection, paginationInfo, loadMore) => (
											<_Fragment>
												{collection?.map(
													(
														{
															id: idzKxT5CQtu2,
															jQLZtPWi0: jQLZtPWi0zKxT5CQtu2,
															NHqcQ4k6o: NHqcQ4k6ozKxT5CQtu2,
															uBrouiWbv: uBrouiWbvzKxT5CQtu2,
															WxefFDjNT: WxefFDjNTzKxT5CQtu2,
															yn3XiFF9S: yn3XiFF9SzKxT5CQtu2,
															zSxRelg24: zSxRelg24zKxT5CQtu2,
														},
														index,
													) => {
														yn3XiFF9SzKxT5CQtu2 ??= "";
														WxefFDjNTzKxT5CQtu2 ??= "";
														NHqcQ4k6ozKxT5CQtu2 ??= "";
														zSxRelg24zKxT5CQtu2 ??= "";
														jQLZtPWi0zKxT5CQtu2 ??= "";
														const textContent = prefix(
															toDateString(
																uBrouiWbvzKxT5CQtu2,
																activeLocaleCode,
															),
															"Last Updated: ",
														);
														return (
															<LayoutGroup id={`zKxT5CQtu-${idzKxT5CQtu2}`}>
																<PathVariablesContext.Provider
																	value={{
																		jQLZtPWi0: jQLZtPWi0zKxT5CQtu2,
																	}}
																>
																	<motion.div
																		className={"framer-1g0lvgr"}
																		layoutDependency={layoutDependency}
																		layoutId={"Ga6vmWL_0"}
																	>
																		<motion.div
																			className={"framer-1tcfik8"}
																			data-framer-name={"Top"}
																			layoutDependency={layoutDependency}
																			layoutId={"cwn7BoR_3"}
																		>
																			<motion.div
																				className={"framer-1xv8nr"}
																				data-framer-name={"Content"}
																				layoutDependency={layoutDependency}
																				layoutId={"MuC7vDbMm"}
																			>
																				<motion.div
																					className={"framer-w3x3ds"}
																					data-framer-name={"Tag & Title"}
																					layoutDependency={layoutDependency}
																					layoutId={"udSkwuFtu"}
																				>
																					<ComponentViewportProvider
																						height={40}
																						y={
																							(componentViewport?.y || 0) +
																							0 +
																							200 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0 +
																							0
																						}
																						{...addPropertyOverrides(
																							{
																								qQZf7tA7c: {
																									y:
																										(componentViewport?.y ||
																											0) +
																										0 +
																										180 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0,
																								},
																								xA_6Q6tyB: {
																									y:
																										(componentViewport?.y ||
																											0) +
																										0 +
																										160 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0 +
																										0,
																								},
																							},
																							baseVariant,
																							gestureVariant,
																						)}
																					>
																						<SmartComponentScopedContainer
																							className={
																								"framer-14no0ss-container"
																							}
																							layoutDependency={
																								layoutDependency
																							}
																							layoutId={"m2fJ4g3ve-container"}
																							nodeId={"m2fJ4g3ve"}
																							rendersWithMotion={true}
																							scopeId={"LUMOn5XcA"}
																						>
																							{_jsx(stdin_default, {
																								aZ7GvMqIl: "Acorn",
																								height: "100%",
																								id: "m2fJ4g3ve",
																								KS7KLFqN8: WxefFDjNTzKxT5CQtu2,
																								layoutId: "m2fJ4g3ve",
																								rQKAY6456: yn3XiFF9SzKxT5CQtu2,
																								variant: "AksRoqhcS",
																								width: "100%",
																								xAPRy8bad: 0,
																							})}
																						</SmartComponentScopedContainer>
																					</ComponentViewportProvider>
																					<motion.div
																						className={"framer-1ar6zlg"}
																						data-framer-name={"Title"}
																						layoutDependency={layoutDependency}
																						layoutId={"xQ3IWEMmL"}
																					>
																						<RichText
																							__fromCanvasComponent={true}
																							className={"framer-1hvwplh"}
																							data-framer-name={"Text"}
																							fonts={["Inter"]}
																							layoutDependency={
																								layoutDependency
																							}
																							layoutId={"pJRciQCjL"}
																							style={{
																								"--extracted-gdpscs":
																									"rgb(255, 255, 255)",
																								"--framer-link-text-color":
																									"rgb(0, 153, 255)",
																								"--framer-link-text-decoration":
																									"underline",
																							}}
																							text={NHqcQ4k6ozKxT5CQtu2}
																							verticalAlignment={"top"}
																							withExternalLayout={true}
																						>
																							<React.Fragment>
																								<motion.h1
																									className={
																										"framer-styles-preset-1idioqq"
																									}
																									data-styles-preset={
																										"ABKs9wxVy"
																									}
																									style={{
																										"--framer-text-alignment":
																											"left",
																										"--framer-text-color":
																											"var(--extracted-gdpscs, rgb(255, 255, 255))",
																									}}
																								>
																									<motion.span
																										data-text-fill={"true"}
																										style={{
																											backgroundImage:
																												"linear-gradient(90deg, var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255)) 0%, var(--token-14f74354-f5bc-49c1-9486-2936a231e276, rgba(255, 255, 255, 0.3)) 350%)",
																										}}
																									>
																										{"Terms & Conditions"}
																									</motion.span>
																								</motion.h1>
																							</React.Fragment>
																						</RichText>
																					</motion.div>
																				</motion.div>
																				<motion.div
																					className={"framer-xg2efc"}
																					data-framer-name={"Date"}
																					layoutDependency={layoutDependency}
																					layoutId={"pbq_31dgw"}
																				>
																					<RichText
																						__fromCanvasComponent={true}
																						className={"framer-16bncf4"}
																						data-framer-name={"Text"}
																						fonts={["Inter"]}
																						layoutDependency={layoutDependency}
																						layoutId={"GG12Z8IwT"}
																						style={{
																							"--framer-link-text-color":
																								"rgb(0, 153, 255)",
																							"--framer-link-text-decoration":
																								"underline",
																						}}
																						text={textContent}
																						verticalAlignment={"top"}
																						withExternalLayout={true}
																						{...addPropertyOverrides(
																							{
																								qQZf7tA7c: {
																									children: (
																										<React.Fragment>
																											<motion.p
																												className={
																													"framer-styles-preset-x0s9r5"
																												}
																												data-styles-preset={
																													"QhK6qqT5U"
																												}
																												style={{
																													"--framer-text-alignment":
																														"left",
																												}}
																											>
																												{"Last Updated: "}
																											</motion.p>
																										</React.Fragment>
																									),
																								},
																								xA_6Q6tyB: {
																									children: (
																										<React.Fragment>
																											<motion.p
																												className={
																													"framer-styles-preset-x0s9r5"
																												}
																												data-styles-preset={
																													"QhK6qqT5U"
																												}
																												style={{
																													"--framer-text-alignment":
																														"left",
																												}}
																											>
																												{"Last Updated: "}
																											</motion.p>
																										</React.Fragment>
																									),
																								},
																							},
																							baseVariant,
																							gestureVariant,
																						)}
																					>
																						<React.Fragment>
																							<motion.p
																								className={
																									"framer-styles-preset-x0s9r5"
																								}
																								data-styles-preset={"QhK6qqT5U"}
																								style={{
																									"--framer-text-alignment":
																										"left",
																								}}
																							>
																								{
																									"Last Updated: Oct 15, 2024 at 12:00 AM"
																								}
																							</motion.p>
																						</React.Fragment>
																					</RichText>
																				</motion.div>
																			</motion.div>
																		</motion.div>
																		<motion.div
																			className={"framer-12em2sk"}
																			data-framer-name={"Bottom"}
																			layoutDependency={layoutDependency}
																			layoutId={"HYtyYxB1y"}
																		>
																			<RichText
																				__fromCanvasComponent={true}
																				className={"framer-1bzd4g9"}
																				data-framer-name={"Text"}
																				fonts={["Inter"]}
																				layoutDependency={layoutDependency}
																				layoutId={"OyNVeoZaA"}
																				stylesPresetsClassNames={{
																					a: "framer-styles-preset-68ruwb",
																					blockquote:
																						"framer-styles-preset-1h1u2ja",
																					code: "framer-styles-preset-1uqcokq",
																					h3: "framer-styles-preset-pyuk04",
																					h4: "framer-styles-preset-1ing3ma",
																					h5: "framer-styles-preset-voew0c",
																					p: "framer-styles-preset-x0s9r5",
																				}}
																				verticalAlignment={"top"}
																				withExternalLayout={true}
																			>
																				{zSxRelg24zKxT5CQtu2}
																			</RichText>
																		</motion.div>
																	</motion.div>
																</PathVariablesContext.Provider>
															</LayoutGroup>
														);
													},
												)}
											</_Fragment>
										)}
									</QueryData>
								</ChildrenCanSuspend>
							</motion.div>
						</motion.div>
					</motion.section>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css8 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PSZhG.framer-1e9ixoh, .framer-PSZhG .framer-1e9ixoh { display: block; }",
	".framer-PSZhG.framer-wka6op { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 120px; height: min-content; justify-content: flex-start; max-width: 1440px; overflow: visible; padding: 0px 0px 160px 0px; position: relative; width: 1200px; }",
	".framer-PSZhG .framer-bnv7tl { flex: none; height: 80px; overflow: hidden; position: relative; width: 100%; }",
	".framer-PSZhG .framer-e7up6d { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; max-width: 980px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-1jlcn1n { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-1g0lvgr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-1tcfik8 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 38px; height: min-content; justify-content: center; max-width: 980px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-1xv8nr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-w3x3ds { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 34px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-14no0ss-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-PSZhG .framer-1ar6zlg { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-1hvwplh { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-PSZhG .framer-xg2efc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; max-width: 500px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-16bncf4 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; z-index: 1; }",
	".framer-PSZhG .framer-12em2sk { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PSZhG .framer-1bzd4g9 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-PSZhG.framer-v-z80r7a.framer-wka6op { gap: 100px; padding: 0px 0px 120px 0px; width: 810px; }",
	".framer-PSZhG.framer-v-z80r7a .framer-e7up6d { padding: 0px 50px 0px 50px; }",
	".framer-PSZhG.framer-v-1rumc1j.framer-wka6op { gap: 80px; padding: 0px 0px 120px 0px; width: 200px; }",
	".framer-PSZhG.framer-v-1rumc1j .framer-e7up6d { padding: 0px 30px 0px 30px; }",
	".framer-PSZhG.framer-v-1rumc1j .framer-1tcfik8 { max-width: 460px; }",
	...css4,
	...css2,
	...css,
	...css3,
	...css7,
	...css5,
	...css6,
];
var FramerLUMOn5XcA = withCSS(Component, css8, "framer-PSZhG");
var stdin_default3 = FramerLUMOn5XcA;
FramerLUMOn5XcA.displayName = "Main-Terms&Conditions";
FramerLUMOn5XcA.defaultProps = {
	height: 2929,
	width: 1200,
};
addPropertyControls(FramerLUMOn5XcA, {
	variant: {
		options: ["zM2zLXAnh", "qQZf7tA7c", "xA_6Q6tyB"],
		optionTitles: ["L", "M", "S"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerLUMOn5XcA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagPrimaryTagFonts,
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts6),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:main-terms-conditions
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "xA_6Q6tyB",
	md: "qQZf7tA7c",
	xl: "zM2zLXAnh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders MainTermsConditionsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var main_terms_conditions_default = ComponentWithRoot;
export { main_terms_conditions_default as default };
