// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * star1?: boolean // Star 1
 * star2?: boolean // Star 2
 * star3?: boolean // Star 3
 * star4?: boolean // Star 4
 * star5?: boolean // Star 5
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-JOQ27WRR.js";
import { routes } from "../chunks/chunk-XIXCBJDO.js";

// virtual:interactive-components/star-rating
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lkA8VjuJh0KnVAJqjGvS/NajmT1r9sVYX6hvUCmAp/Q5CZcxuFO.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-lH2ML";
var variantClassNames = {
	ACX9bYcuD: "framer-v-1tsfb5f",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	height,
	id,
	star1,
	star2,
	star3,
	star4,
	star5,
	text,
	width,
	...props
}) => {
	return {
		...props,
		D3LBMPMda: star2 ?? props.D3LBMPMda ?? true,
		EL6OHVjhu: text ?? props.EL6OHVjhu ?? "200+ Agencies Rated",
		M3Dyd2AtH: star1 ?? props.M3Dyd2AtH ?? true,
		N76rLfG8r: star4 ?? props.N76rLfG8r ?? true,
		OHbpr7lSd: star5 ?? props.OHbpr7lSd ?? true,
		OijM7rrfw: star3 ?? props.OijM7rrfw ?? true,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		M3Dyd2AtH,
		D3LBMPMda,
		OijM7rrfw,
		N76rLfG8r,
		OHbpr7lSd,
		EL6OHVjhu,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ACX9bYcuD",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1tsfb5f",
							className2,
							classNames,
						)}
						data-framer-name={"Primary"}
						layoutDependency={layoutDependency}
						layoutId={"ACX9bYcuD"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
					>
						<motion.div
							className={"framer-xcgqdb"}
							data-framer-name={"Stars"}
							layoutDependency={layoutDependency}
							layoutId={"CngMYaquH"}
						>
							{M3Dyd2AtH && (
								<motion.div
									className={"framer-1pfwmg0"}
									data-framer-name={"1"}
									layoutDependency={layoutDependency}
									layoutId={"x4nHbRyBY"}
								>
									<SVG
										className={"framer-pcws0"}
										data-framer-name={"Star"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"JSyGRZXjc"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 9.049 2.927 C 9.348 2.006 10.652 2.006 10.951 2.927 L 12.021 6.219 C 12.155 6.631 12.539 6.91 12.972 6.91 L 16.433 6.91 C 17.402 6.91 17.804 8.149 17.021 8.719 L 14.22 10.753 C 13.87 11.008 13.723 11.459 13.857 11.871 L 14.927 15.163 C 15.226 16.084 14.172 16.851 13.388 16.281 L 10.588 14.247 C 10.237 13.992 9.763 13.992 9.412 14.247 L 6.612 16.281 C 5.828 16.851 4.774 16.084 5.073 15.163 L 6.143 11.871 C 6.277 11.459 6.13 11.008 5.779 10.753 L 2.979 8.719 C 2.196 8.149 2.598 6.91 3.567 6.91 L 7.028 6.91 C 7.462 6.91 7.845 6.631 7.979 6.219 Z" fill="var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))"></path></svg>'
										}
										svgContentId={8874811582}
										withExternalLayout={true}
									/>
								</motion.div>
							)}
							{D3LBMPMda && (
								<motion.div
									className={"framer-154no10"}
									data-framer-name={"2"}
									layoutDependency={layoutDependency}
									layoutId={"Gxu0fC9Zd"}
								>
									<SVG
										className={"framer-1c0rwqw"}
										data-framer-name={"Star"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"bguF4Up1S"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 9.049 2.927 C 9.348 2.006 10.652 2.006 10.951 2.927 L 12.021 6.219 C 12.155 6.631 12.539 6.91 12.972 6.91 L 16.433 6.91 C 17.402 6.91 17.804 8.149 17.021 8.719 L 14.22 10.753 C 13.87 11.008 13.723 11.459 13.857 11.871 L 14.927 15.163 C 15.226 16.084 14.172 16.851 13.388 16.281 L 10.588 14.247 C 10.237 13.992 9.763 13.992 9.412 14.247 L 6.612 16.281 C 5.828 16.851 4.774 16.084 5.073 15.163 L 6.143 11.871 C 6.277 11.459 6.13 11.008 5.779 10.753 L 2.979 8.719 C 2.196 8.149 2.598 6.91 3.567 6.91 L 7.028 6.91 C 7.462 6.91 7.845 6.631 7.979 6.219 Z" fill="var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))"></path></svg>'
										}
										svgContentId={8874811582}
										withExternalLayout={true}
									/>
								</motion.div>
							)}
							{OijM7rrfw && (
								<motion.div
									className={"framer-1xpr9o3"}
									data-framer-name={"3"}
									layoutDependency={layoutDependency}
									layoutId={"DFnaXOZ9G"}
								>
									<SVG
										className={"framer-13i38ma"}
										data-framer-name={"Star"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"R_JpHOekP"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 9.049 2.927 C 9.348 2.006 10.652 2.006 10.951 2.927 L 12.021 6.219 C 12.155 6.631 12.539 6.91 12.972 6.91 L 16.433 6.91 C 17.402 6.91 17.804 8.149 17.021 8.719 L 14.22 10.753 C 13.87 11.008 13.723 11.459 13.857 11.871 L 14.927 15.163 C 15.226 16.084 14.172 16.851 13.388 16.281 L 10.588 14.247 C 10.237 13.992 9.763 13.992 9.412 14.247 L 6.612 16.281 C 5.828 16.851 4.774 16.084 5.073 15.163 L 6.143 11.871 C 6.277 11.459 6.13 11.008 5.779 10.753 L 2.979 8.719 C 2.196 8.149 2.598 6.91 3.567 6.91 L 7.028 6.91 C 7.462 6.91 7.845 6.631 7.979 6.219 Z" fill="var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))"></path></svg>'
										}
										svgContentId={8874811582}
										withExternalLayout={true}
									/>
								</motion.div>
							)}
							{N76rLfG8r && (
								<motion.div
									className={"framer-1ljkkj1"}
									data-framer-name={"4"}
									layoutDependency={layoutDependency}
									layoutId={"KcjPDNOon"}
								>
									<SVG
										className={"framer-bo5w6t"}
										data-framer-name={"Star"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"ghAU3fP4C"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 9.049 2.927 C 9.348 2.006 10.652 2.006 10.951 2.927 L 12.021 6.219 C 12.155 6.631 12.539 6.91 12.972 6.91 L 16.433 6.91 C 17.402 6.91 17.804 8.149 17.021 8.719 L 14.22 10.753 C 13.87 11.008 13.723 11.459 13.857 11.871 L 14.927 15.163 C 15.226 16.084 14.172 16.851 13.388 16.281 L 10.588 14.247 C 10.237 13.992 9.763 13.992 9.412 14.247 L 6.612 16.281 C 5.828 16.851 4.774 16.084 5.073 15.163 L 6.143 11.871 C 6.277 11.459 6.13 11.008 5.779 10.753 L 2.979 8.719 C 2.196 8.149 2.598 6.91 3.567 6.91 L 7.028 6.91 C 7.462 6.91 7.845 6.631 7.979 6.219 Z" fill="var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))"></path></svg>'
										}
										svgContentId={8874811582}
										withExternalLayout={true}
									/>
								</motion.div>
							)}
							{OHbpr7lSd && (
								<motion.div
									className={"framer-106sp8v"}
									data-framer-name={"5"}
									layoutDependency={layoutDependency}
									layoutId={"uNqflDddi"}
								>
									<SVG
										className={"framer-12txoz1"}
										data-framer-name={"Star"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"s6IuJ6X5D"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><path d="M 9.049 2.927 C 9.348 2.006 10.652 2.006 10.951 2.927 L 12.021 6.219 C 12.155 6.631 12.539 6.91 12.972 6.91 L 16.433 6.91 C 17.402 6.91 17.804 8.149 17.021 8.719 L 14.22 10.753 C 13.87 11.008 13.723 11.459 13.857 11.871 L 14.927 15.163 C 15.226 16.084 14.172 16.851 13.388 16.281 L 10.588 14.247 C 10.237 13.992 9.763 13.992 9.412 14.247 L 6.612 16.281 C 5.828 16.851 4.774 16.084 5.073 15.163 L 6.143 11.871 C 6.277 11.459 6.13 11.008 5.779 10.753 L 2.979 8.719 C 2.196 8.149 2.598 6.91 3.567 6.91 L 7.028 6.91 C 7.462 6.91 7.845 6.631 7.979 6.219 Z" fill="var(--token-59e77027-930e-45f7-94aa-a8ffadf9e382, rgb(255, 255, 255))"></path></svg>'
										}
										svgContentId={8874811582}
										withExternalLayout={true}
									/>
								</motion.div>
							)}
						</motion.div>
						<motion.div
							className={"framer-ligrzs"}
							data-framer-name={"Text"}
							layoutDependency={layoutDependency}
							layoutId={"j_3b2PJvc"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1676tla"}
								data-framer-name={"Text"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"XMN21Txwn"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={EL6OHVjhu}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-x0s9r5"}
										data-styles-preset={"QhK6qqT5U"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-8f8054d9-8a09-4e7e-b957-8a76557c5e75, rgba(255, 255, 255, 0.6)))",
										}}
									>
										{"200+ Agencies Rated"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lH2ML.framer-19dxl8i, .framer-lH2ML .framer-19dxl8i { display: block; }",
	".framer-lH2ML.framer-1tsfb5f { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 3px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 180px; }",
	".framer-lH2ML .framer-xcgqdb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-lH2ML .framer-1pfwmg0, .framer-lH2ML .framer-154no10, .framer-lH2ML .framer-1xpr9o3, .framer-lH2ML .framer-1ljkkj1, .framer-lH2ML .framer-106sp8v { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-lH2ML .framer-pcws0, .framer-lH2ML .framer-1c0rwqw, .framer-lH2ML .framer-13i38ma, .framer-lH2ML .framer-bo5w6t, .framer-lH2ML .framer-12txoz1 { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-lH2ML .framer-ligrzs { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-lH2ML .framer-1676tla { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lH2ML.framer-1tsfb5f, .framer-lH2ML .framer-xcgqdb, .framer-lH2ML .framer-1pfwmg0, .framer-lH2ML .framer-154no10, .framer-lH2ML .framer-1xpr9o3, .framer-lH2ML .framer-1ljkkj1, .framer-lH2ML .framer-106sp8v, .framer-lH2ML .framer-ligrzs { gap: 0px; } .framer-lH2ML.framer-1tsfb5f > * { margin: 0px; margin-bottom: calc(3px / 2); margin-top: calc(3px / 2); } .framer-lH2ML.framer-1tsfb5f > :first-child { margin-top: 0px; } .framer-lH2ML.framer-1tsfb5f > :last-child { margin-bottom: 0px; } .framer-lH2ML .framer-xcgqdb > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-lH2ML .framer-xcgqdb > :first-child, .framer-lH2ML .framer-1pfwmg0 > :first-child, .framer-lH2ML .framer-154no10 > :first-child, .framer-lH2ML .framer-1xpr9o3 > :first-child, .framer-lH2ML .framer-1ljkkj1 > :first-child, .framer-lH2ML .framer-106sp8v > :first-child, .framer-lH2ML .framer-ligrzs > :first-child { margin-left: 0px; } .framer-lH2ML .framer-xcgqdb > :last-child, .framer-lH2ML .framer-1pfwmg0 > :last-child, .framer-lH2ML .framer-154no10 > :last-child, .framer-lH2ML .framer-1xpr9o3 > :last-child, .framer-lH2ML .framer-1ljkkj1 > :last-child, .framer-lH2ML .framer-106sp8v > :last-child, .framer-lH2ML .framer-ligrzs > :last-child { margin-right: 0px; } .framer-lH2ML .framer-1pfwmg0 > *, .framer-lH2ML .framer-154no10 > *, .framer-lH2ML .framer-1xpr9o3 > *, .framer-lH2ML .framer-1ljkkj1 > *, .framer-lH2ML .framer-106sp8v > *, .framer-lH2ML .framer-ligrzs > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	...css,
];
var FramerQ5CZcxuFO = withCSS(Component, css2, "framer-lH2ML");
var stdin_default = FramerQ5CZcxuFO;
FramerQ5CZcxuFO.displayName = "Interactive Components/Star Rating";
FramerQ5CZcxuFO.defaultProps = {
	height: 49,
	width: 180,
};
addPropertyControls(FramerQ5CZcxuFO, {
	M3Dyd2AtH: {
		defaultValue: true,
		title: "Star 1",
		type: ControlType.Boolean,
	},
	D3LBMPMda: {
		defaultValue: true,
		title: "Star 2",
		type: ControlType.Boolean,
	},
	OijM7rrfw: {
		defaultValue: true,
		title: "Star 3",
		type: ControlType.Boolean,
	},
	N76rLfG8r: {
		defaultValue: true,
		title: "Star 4",
		type: ControlType.Boolean,
	},
	OHbpr7lSd: {
		defaultValue: true,
		title: "Star 5",
		type: ControlType.Boolean,
	},
	EL6OHVjhu: {
		defaultValue: "200+ Agencies Rated",
		displayTextArea: true,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerQ5CZcxuFO,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:interactive-components/star-rating
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders StarRatingFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var star_rating_default = ComponentWithRoot;
export { star_rating_default as default };
