// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 48f6b4f835a2a89a "Reeva - Finally, something for your saved reels", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * file?: string // File
}} Props

 */
import { Video } from "../chunks/chunk-G73PZF75.js";
import { routes } from "../chunks/chunk-XIXCBJDO.js";

// virtual:card/video-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lTg03YWj3iLBMMQAE08G/hIwh7ceLFdSvjo5RFSVF/QxYU5fGGT.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	cx,
	getFonts,
	getPropertyControls,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var VideoFonts = getFonts(Video);
var VideoControls = getPropertyControls(Video);
var serializationHash = "framer-JQhzw";
var variantClassNames = {
	ZNblBMiVc: "framer-v-zw81sd",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 300,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ file, height, id, width, ...props }) => {
	return {
		...props,
		XeTTYbda0:
			file ??
			props.XeTTYbda0 ??
			"https://framerusercontent.com/assets/8qsenQIIXYW3mI4IYIYBv9PMtkU.mp4",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, XeTTYbda0, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ZNblBMiVc",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-zw81sd",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"ZNblBMiVc"}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-a9883d9b-c1bd-4bd9-be15-284cd72e1b1f, rgba(255, 255, 255, 0.07))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(2px)",
							backgroundColor:
								"var(--token-74f48371-76c0-476a-a319-1331b3a438c2, rgb(8, 8, 8))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							WebkitBackdropFilter: "blur(2px)",
							...style,
						}}
					>
						<motion.div
							className={"framer-1ljqxsk"}
							data-framer-name={"Content"}
							layoutDependency={layoutDependency}
							layoutId={"ZNblBMiVcjxfwA2AbE"}
							style={{
								borderBottomLeftRadius: 22,
								borderBottomRightRadius: 22,
								borderTopLeftRadius: 22,
								borderTopRightRadius: 22,
							}}
						>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-l5rkck-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"W0TcqKy_V-container"}
									nodeId={"W0TcqKy_V"}
									rendersWithMotion={true}
									scopeId={"QxYU5fGGT"}
								>
									<Video
										backgroundColor={"rgba(0, 0, 0, 0)"}
										borderRadius={0}
										bottomLeftRadius={0}
										bottomRightRadius={0}
										controls={false}
										height={"100%"}
										id={"W0TcqKy_V"}
										isMixedBorderRadius={false}
										layoutId={"W0TcqKy_V"}
										loop={true}
										muted={true}
										objectFit={"cover"}
										playing={true}
										posterEnabled={true}
										srcFile={XeTTYbda0}
										srcType={"Upload"}
										srcUrl={
											"https://framerusercontent.com/assets/MLWPbW1dUQawJLhhun3dBwpgJak.mp4"
										}
										startTime={16.8}
										style={{
											height: "100%",
											width: "100%",
										}}
										topLeftRadius={0}
										topRightRadius={0}
										volume={25}
										width={"100%"}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion.div
								background={{
									alt: "",
									fit: "fill",
								}}
								className={"framer-pa49co"}
								data-border={true}
								data-framer-name={"Border"}
								layoutDependency={layoutDependency}
								layoutId={"fjbPE5StS"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-082d630a-c036-4f77-8c8d-5d7b4650e064, rgba(255, 255, 255, 0.08))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 21,
									borderBottomRightRadius: 21,
									borderTopLeftRadius: 21,
									borderTopRightRadius: 21,
								}}
							/>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JQhzw.framer-1g68r4h, .framer-JQhzw .framer-1g68r4h { display: block; }",
	".framer-JQhzw.framer-zw81sd { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 700px; justify-content: center; padding: 10px; position: relative; width: 1200px; }",
	".framer-JQhzw .framer-1ljqxsk { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 100%; justify-content: center; overflow: hidden; padding: 1px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-JQhzw .framer-l5rkck-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; }",
	".framer-JQhzw .framer-pa49co { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 100% / 2); width: 100%; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-JQhzw.framer-zw81sd, .framer-JQhzw .framer-1ljqxsk { gap: 0px; } .framer-JQhzw.framer-zw81sd > *, .framer-JQhzw .framer-1ljqxsk > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-JQhzw.framer-zw81sd > :first-child, .framer-JQhzw .framer-1ljqxsk > :first-child { margin-left: 0px; } .framer-JQhzw.framer-zw81sd > :last-child, .framer-JQhzw .framer-1ljqxsk > :last-child { margin-right: 0px; } }",
	'.framer-JQhzw[data-border="true"]::after, .framer-JQhzw [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerQxYU5fGGT = withCSS(Component, css, "framer-JQhzw");
var stdin_default = FramerQxYU5fGGT;
FramerQxYU5fGGT.displayName = "Card/Video Card";
FramerQxYU5fGGT.defaultProps = {
	height: 700,
	width: 1200,
};
addPropertyControls(FramerQxYU5fGGT, {
	XeTTYbda0: VideoControls?.["srcFile"] && {
		...VideoControls["srcFile"],
		__defaultAssetReference:
			"data:framer/asset-reference,8qsenQIIXYW3mI4IYIYBv9PMtkU.mp4?originalFilename=Framer%C3%AF%C2%BC%C2%9A+All+Design%2C+No+Code%2C+Real+Websites.mp4",
		description: void 0,
		hidden: void 0,
		title: "File",
	},
});
addFonts(
	FramerQxYU5fGGT,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card/video-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"48f6b4f835a2a89a3c18bb75fe4f3550068fb798fed19a2a19091b5f3e55584e"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var video_card_default = ComponentWithRoot;
export { video_card_default as default };
